### ISSUE TITLE
[🐞] Error: Missing Qwik City Env Data

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#5927] opened 2024-03-03 13:26 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to run my program and I get this error:

```
Error: Missing Qwik City Env Data
    at AsyncFunction.Ed (file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:15:10885)
    at AsyncFunction.vi (file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:10:5894)
    at AsyncFunction.$e (file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:10:5828)
    at file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:15:2939
    at Z (file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:7:1519)
    at file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:15:2806
    at file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:8:4709
    at An (file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:7:1437)
    at cn (file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:8:4702)
    at qc (file:///Holism/SiteQwik/server/q-HFmeDqJ8.js:8:9151)
```

What data can I get from this vague message? Where should I go to debug it?

Could you please provide more details?

### Reproduction

none

### System Info

```shell
System:
    OS: Linux 6.5 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 8.29 GB / 15.35 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.4.0 - /usr/local/bin/npm
  Browsers:
    Chromium: 122.0.6261.57
  npmPackages:
    @builder.io/partytown: ^0.9.2 => 0.9.2 
    @builder.io/qwik: ^1.4.5 => 1.4.5 
    @builder.io/qwik-auth: ^0.1.3 => 0.1.3 
    @builder.io/qwik-city: ^1.4.5 => 1.4.5 
    undici: ^6.6.2 => 6.6.2 
    vite: ^5.1.4 => 5.1.4
```

**Comment by PatrickJS** [comment] 2024-05-06 03:15
duplicate of https://github.com/QwikDev/qwik/issues/5939

**Closed by PatrickJS** 2024-05-06 03:15 UTC
Labels: TYPE: bug, STATUS-1: needs triage
