### ISSUE TITLE
[🐞]Store array update does not rerender list

### ISSUE THREAD

**Issue by Domniq** [QwikDev/qwik#5662] opened 2024-01-02 11:06 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

There is a problem with rendering updated values using list { store.array.map }
I can change values only one or twice, depending on code usage after that any further modification is not updating values visually, **however store values are changed**
I've created thread on discord https://discord.com/channels/842438759945601056/1191080926554361992
I managed to find a solution and it's working but it should be used this way

As you can see on the image store.values are different than those that are visible using .map
![problem](https://github.com/BuilderIO/qwik/assets/16792717/0f67a8ca-7407-4c53-a2c2-29eecf946d97)

 As i mentioned earlier 1 or 2 operations are displayed any further only updates store values but not items rendered via { store.array.map }

IMPORTANT:
This code is working in stackblitz https://stackblitz.com/edit/qwik-starter-kzdpd9 (version 1.2.11)

### Reproduction

https://qwik.builder.io/playground/#v=1.3.1&f=7VjdbtMwFH4VSxNyAnVI0r80I5UGmgSIAdLgapqQUztrWLdEo6Xrqt7s3fZenGMnTtqU%2FYB2MWmbFDmxfc7xd%2F4%2BtxY0ftCteUp5RjfdVi0YWlUv1kPV3O8RV0reV2id7yBqTyDNoW1xgATBSEVY8IMWvGHlKt8B8nsFZsEklDFRxRGWkLmoDMpI2FB%2BdLwaIv64HyTUVh4VoC2VZdQPuOvLfpe1AzdgHd7rMt5ORmzQd92BL%2BRADHzaKuym309vrrkg84WQo3E2X1CywlM9TJ5Xyds7nZ3NJlhotojiXhz3ZdBmXLY56%2FQ9ybgbJ2zkcVAi3F7P6zZMu%2BL5zXUGjGGLwH7cSdpeIFgwij3WEd2EDQYJZ57vxnGvG7STON4icA64XcnzlBuJx%2FBUwyV4TuahboRYJoy7UlH4SlM77fGhRaletC1FkIyWFI0Cm8mhBYUkmcjLXXLCQYvn5jD8OYNenywYNiaIFIimHDgQi%2BV0LuX5LhCkSzZPxXQckq6LO%2BjKJMotGvDJRHqhGzVQ32wyOwNxSnMHFedcCDhESHxlB7QjyAawKr8k0MXhwDuijf%2FlFLvgIp1ByKndFY8ByycZbNxJkmQX6IUy1XPdFzVLsVz4wz0hkO5AKfBrE6kiwJhzEcX%2BQAHsiIJxP9BzlMCpRnKcYa5GtEwKaqoFFhPF8ityu9TJBuoslWb2ClWb24ApM3hLeKJQ7ot0ei8cJSz8XyAP%2BW%2BpkWyBTEATP9wCZzE02aq2OlXVcuDSYVnF%2B6KlWJ1SpPPH%2BONULqKlml09biIpjfmwLMELJxUr5Apr001Y1L2iOofGphKCqK%2BLWQs524aGUXxX90p9RNq0c7j8ePjls6OLDhyxjOo3r3HfZqPEimR4hMmBkNzVYDS90OVOMfIIGLQmfw5w7f2JxOHbxQdhVdlpA18m778dfFLX2GKNKolpQixc4gD5nMHFVjP7IXG1nlJTiVbTJBKpZXqxbrzWAZ%2BOnWSSZRd6iFef7Azc8ZJYkCfqjzBMGRy8Ip5t41O92s60ZEt22Ul0b6jMVJ8LtzSiNp%2F9GhtvA8qlAL0V4KLAIXA7CDAO2AiS5jExbMKCvZR95SGuqBL8L77YMHItPLWnRHMyFUgha8cwJeDuQHr0Ez1SdJU4%2FFNwwE8R%2B3w0hrIGxzcFzYgHc0cAKomiNZBtUxo2BR4pIcc1n%2BiAK1jJ1shbc6UJxuerztO76vwB

### Steps to reproduce

Here are different ways to modify store.arrays:
    // Not working #1 (can modify 1 element)
    const category: PartCategoryData =
    {
      id: id.value,
      name: name.value
    }
    
    store.categories.forEach((c, index) => {
      if (c.id === category.id)
        store.categories[index] = category;
    });

    // Not working #2 (can modify 1 element)
    store.categories = store.categories.map((category) => {
      if (category.id === id.value) {
        return {
          ...category, name: name.value
        };
      }
    
      return category;
    });

    // Not working #3 (can modify 1 element)
    const modified = store.categories.map((category) => {
      if (category.id === id.value) {
        return {
          ...category, name: name.value
        };
      }
    
      return category;
    });
    
    store.categories.splice(0, store.categories.length, ...modified);

    // Not working #4 (can modify 2 elements)
    const selectedCategory = store.categories.find(category => category.id === id.value)
    
    if (selectedCategory) {
      selectedCategory.name = name.value;
    }

    // Not working #5 (can modify 2 elements)
    store.categories.forEach(category => {
      if (category.id === id.value) {
        category.name = name.value;
      }
    });

    // Not working #6 (can modify 2 elements)
    for (const category of store.categories) {
      if (category.id === id.value) {
        category.name = name.value;
        break; // If you only want to modify the first matching item
      }
    }

    // Not working #7 (can modify 1 element)
    store.categories = store.categories
    .filter(category => !(category.id === id.value))
    .concat(store.categories.filter(category => category.id === id.value)
      .map(category => ({ ...category, name: name.value }))
    );

### System Info

```shell
Windows 11, Opera browser, mozilla, edge
In my project im using Qwik ^1.2.15
```

### Additional Information

You can find more on discord thread https://discord.com/channels/842438759945601056/1191080926554361992

**Comment by wmertens** [comment] 2024-01-02 11:28
Did Qwik 1.3.2 fix anything?

**Comment by Domniq** [comment] 2024-01-02 11:56
Yup, still an issue
![image](https://github.com/BuilderIO/qwik/assets/16792717/d26d3be3-5f2d-4bd8-b62d-61dadd676892)

I manage to find workaround by clearing store and assigning it once again after 'empty' await 
![image](https://github.com/BuilderIO/qwik/assets/16792717/a981884f-a262-4c3e-b26d-d4c72e98c8ca)

Without await Promise it does not update displayed items, only store gets updated
This version if working fully https://stackblitz.com/edit/qwik-starter-fkqkjj

**Comment by wmertens** [comment] 2024-01-02 12:13
It seems that 1.2.13 works correct, right?

**Comment by Domniq** [comment] 2024-01-02 12:21
Stackblitz link I've provided uses
"@builder.io/qwik": "^1.2.11",
"@builder.io/qwik-city": "^1.2.11",
It working fine there

**Comment by Domniq** [comment] 2024-01-02 12:30
I did some test on qwik@1.2.11 and it's not working there.
So only in Stackblitz with qwik 1.2.11 it's working, might it be environment issue?

**Comment by wmertens** [comment] 2024-01-02 12:35
Very odd. Ideally we'd have a minimal e2e test case but if it even differs across environments...

**Comment by wmertens** [comment] 2024-01-02 12:45
Ok in that case the playground is equally valid.

**Comment by Domniq** [comment] 2024-01-02 12:50
Yes, currently im using Code Compare for file difference with node_modules because everything matches except node_modules folder
npm create qwik@1.2.11 and downloaded stackblitz project are compared

**Comment by Domniq** [comment] 2024-01-02 13:05
package-lock.json differs https://www.diffchecker.com/TwlJfa9s/
On the left npm create qwik@1.2.11, on the right taken from stackblitz

**Comment by wmertens** [comment] 2024-01-17 17:08
Can you make a minimal playground repro that always triggers the bug? I'm having trouble reproducing it.

**Comment by Domniq** [comment] 2024-01-18 14:24
Here is minimalistic version with several solutions to save updated values in store
Quick descripiton:
- you can add new entry in 'Add new' form
- when you click on green label you can edit entry in 'Edit' form
- when you click on green you can remove entry

I've tested it few time on 1.3.5 qwik.builder.io/playground
removing - working
adding - working
editing - works only for 1 / 2 items

In my project I have found that sometimes wrong index / key is removed

`import { type Signal, component$, useSignal, useStore, useTask$ } from '@builder.io/qwik';

export type PartCategoryData = {
  id: string,
  name: string
}

export default component$(() => {
  const store = useStore<{categories: PartCategoryData[]}>(
  {
    categories: [
      { id: '28a02e75-3808-4a65-a3fc-970092de9d92', name: 'Exhaust' },
      { id: '28a02e75-3808-4a65-a3fc-970092de9d91', name: 'Battery' },
      { id: 'a1bb7e83-ae3a-471e-a0bf-c1a8a0d06615', name: 'Ignition' },
      { id: '7b4f318d-8cb1-4d5f-99fa-120bb6583fbb', name: 'Suspension' },
    ]
  });

  const id = useSignal<string>('');

  useTask$(({track}) => {
    track(() => store);
    console.log('x');
  });

  return (
    <>
      <div style={'display: flex; gap: 10px; justify-content: space-between; max-width: 500px;'}>
        <div style={'display: flex; flex-direction: column; gap: 4px; padding: 20px; border: 1px solid #d3d3d3; border-radius: 4px; background-color: #fff; width: 100%;'}>
          <h2>Add new</h2>
          <input type='text' id='add_name' placeholder='Category'/>
          <button onClick$={() => Add(store)}>Add</button>
        </div>
        <div style={'display: flex; flex-direction: column; gap: 4px; padding: 20px; border: 1px solid #d3d3d3; border-radius: 4px; background-color: #fff; width: 100%;'}>
          <h2>Edit</h2>
          <input type='text' id='edit_name' placeholder='Category'/>
          <button onClick$={() => Save(store, id)}>Save</button>
        </div>
      </div>

      { store.categories.map((category) =>
        <div key={category.id} style={'display: flex; gap: 10px; justify-content: space-between; max-width: 500px;'}>
          <p style='color: red; cursor: pointer;' onClick$={() => Remove(store, category.id)}>{category.id}</p>
          <p style='color: green; cursor: pointer;' onClick$={() => Select(category, id)}>{category.name}</p>
        </div>
      )}

      {/* { store.categories.map((category,index) => (
        <div key={index} style={'display: flex; gap: 10px; justify-content: space-between; max-width: 500px;'}>
          <p>{category.id}</p>
          <p onClick$={() => Select(category, id)}>{category.name}</p>
        </div>
      ))} */}

      <span style='max-width: 500px;' onClick$={async () => {
          // store.categories = [];
          // await new Promise(resolve => setTimeout(resolve, 0));
          // store.categories = store2.categories;
      }}>{JSON.stringify(store)}</span>
    </>
  );
});

async function Remove(store: {categories: PartCategoryData[]}, id: string) {
  if (!window.confirm('Do you want to remove this item?'))
    return;

  store.categories = store.categories.filter((category) => category.id !== id);
}

function Add(store: {categories: PartCategoryData[]}) {
  const name = document.getElementById('add_name') as HTMLInputElement;

  if (name.value.length > 0) {
    const category: PartCategoryData =
    {
      id: (Math.floor(Math.random() * (10000000 - 100000 + 1)) + 100000).toString(),
      name: name.value
    }

    // store.categories.push(category);

    store.categories = [...store.categories, category];
    name.value = '';
  }
}

function Select(category: PartCategoryData, id: Signal<string>) {
  const name = document.getElementById('edit_name') as HTMLInputElement;
  name.value = category.name;

  id.value = category.id;
  console.log(id.value);
}

function Save(store: {categories: PartCategoryData[]}, id: Signal<string>) {
  const name = document.getElementById('edit_name') as HTMLInputElement;

  if (name.value.length > 0) {
    // Not working #1 (can modify 1 element)
    // const category: PartCategoryData =
    // {
    //   id: id.value,
    //   name: name.value
    // }
    
    // store.categories.forEach((c, index) => {
    //   if (c.id === category.id)
    //     store.categories[index] = category;
    // });


    // Not working #2 (can modify 1 element)
    // store.categories = store.categories.map((category) => {
    //   if (category.id === id.value) {
    //     return {
    //       ...category, name: name.value
    //     };
    //   }
    
    //   return category;
    // });


    // Not working #3 (can modify 1 element)
    // const modified = store.categories.map((category) => {
    //   if (category.id === id.value) {
    //     return {
    //       ...category, name: name.value
    //     };
    //   }
    
    //   return category;
    // });
    
    // store.categories.splice(0, store.categories.length, ...modified);


    // Not working #4 (can modify 2 elements)
    // const selectedCategory = store.categories.find(category => category.id === id.value)
    
    // if (selectedCategory) {
    //   selectedCategory.name = name.value;
    // }


    // Not working #5 (can modify 2 elements)
    // store.categories.forEach(category => {
    //   if (category.id === id.value) {
    //     category.name = name.value;
    //   }
    // });


    // Not working #6 (can modify 2 elements)
    // for (const category of store.categories) {
    //   if (category.id === id.value) {
    //     category.name = name.value;
    //     break; // If you only want to modify the first matching item
    //   }
    // }

    // Not working #7 (can modify 1 element)
    // store.categories = store.categories
    // .filter(category => !(category.id === id.value))
    // .concat(store.categories.filter(category => category.id === id.value)
    //   .map(category => ({ ...category, name: name.value }))
    // );


    const xxx = store.categories;
    for (const category of xxx) {
      if (category.id === id.value) {
        category.name = name.value;
        category.id = id.value;
        break; // If you only want to modify the first matching item
      }
    }

    store.categories = xxx;
    // store.categories = xxx;

    // name.value = '';
    // id.value = '';
  }
}`

**Comment by the-zimmermann** [comment] 2024-01-18 16:50
@Domniq isn't the deep option on useStore change this behavior?

**Comment by wmertens** [comment] 2024-01-19 13:20
@Domniq can I ask you to make the repro smaller, in the playground?

Ideally, you make it so that only a few clicks are needed to trigger the problem, and the app should be as small as possible, no styling or nice content. Just exactly what is needed to trigger.

Here's the playground link to start from: [link](https://qwik.builder.io/playground/#v=1.4.0&f=7Vlrb%2BNEFP3Or5iqQnZK7NpJ07w2RSxUoohdEOVbVSEnYzemaRzlQRNV%2Be%2BcO%2BN5OM6rdBdpEa0UxfbM3HvPfZ3rWEHTaAdW1AjPyKZbtYKhanqx%2FEq9WHwT9W5fhDEFiTj6V3TR7xHAD8h4dLAI6BAuKe%2FkVKGKKypi6hro6xP2BmnOKgTr6Bm%2B8IIsJmkoKZ2S9Lv79RX5gvbjBGvlXQ7gi1DNqbWioBY3G169FbS8i%2Biy4UX1ZOC1m0HQrvG4zds1p5or7lwvh9FiNnfYmqx53TGhOeZ9NEcbX5WPicJ%2Bvxm36l4U1yPvohnGXhT0E28QRhDAg8vLsGGOuXkYpxT05XOa%2FYukHra41xr0Q%2B%2BCNxKv3U4iL6wF%2Ff5lo1VP%2Bn1zzu1iNonHM%2Fuke3xSCWAa%2F5Tn4EveJn145TpOvkozL%2FdF0Ki19h%2BTvCr3qPAj7SG%2FWITOWYqTtNQdCQXSqiidA%2FYzQcvqsGQUL7vsIZp0WBhM8PVPOClNVh41MkQTQm4CzuT14%2FlzHI%2B7IFRL7znl82GHNQLa4aytRNsjgz49nk5lawdZzkaLJxwoZF%2BQ6EnEOZDpsJrQBA0MWQO9JksGW4HiKa%2FTv3rkTSOeLhCYYrdhPtB9lGHjaZIkXRASoWwYBF8XdKUSU7v6jnOiSCgftcKjVNBmSs%2BeQ13FgRd7DhT8gzzvMFg2iIcZ5XXPUenj6Boji5CYDgwpfpFuhEhXunJN4vUUYVAU88UXDOo1T%2BdHIhpj6dshvY3%2BiiWmVZwKXOnGAWDVhU5%2Fsd83Bc%2FH7OK6%2BfWK5BRd8hiveqqSrvyUrz93dkHuJJfh5N6YxrzLBovpjC4EG46nXaeEz2%2FxU2YQsnQGVAUTiMHsk%2FcwFWoelngrhiKNXu4WI4tcXpRWcE6FOlzumPOzg86pCuYuBMuqV3SSePqvuOcQmp8apsqanZ0brN6JFwi5y8rKWuLlGGKYgvrDRLoJNZrX3b3sOnpNabZ01WxGfUrPxupulQWVvHHtEyNu1ax7assamPx0%2B8tHX%2FZOuEhV0HfnZPImmRONUJqoKa%2BdAx12iAKRJxTdksQ4TZh78izmEx%2FxkaTTJ9f5IWOrbMGeIwzK8wzpSDIw12KIo9nyW6dSEarJlizb8y7D7ehO0hHyqlh97LxlJ70exQoRcfaVtlG3lsMGSqMkQREDcg8DrZzFfIy%2B16OYvr5f3XDXtL0Kxlf24%2B8ffhZvlfI10iqCh9b4GAYX4CVy0r6C4xWTFKKUDWWdWE8sU8FI8LsfovnQT0ZZNpVf6VVE9oSoPWMueo%2F4Yx61IfryDQsrFfoUlxV%2FrqaXiuJ4krUZNcVtlT5bYtKfLGZD4wRp6VYP3vk%2BgrN421TaPH2MYOxwaA6A8IIDN%2BpBGSUZl0Um%2BRpXmn67y5dFLQuVKPc0Lz9NOe20SalatRmiplUfm4Sf09hjAhdx8REj63M2faTXtqchg3%2FGeKHEUYdYyOAyOk0mOhYfGehYqc%2BX4a4gk9Eqbm8NWDwBpPjbGbZ4cXkdDYaoH4BQt0ZbHIweUB3poY7YfMAsKYf5nTjq3vK7DGvSR%2BbGVrxqB%2FA6ph6WqFjJGKs2kk06%2FOyFejQq3GMMuWs68C7IRanQBouyYblAH%2F0qaOpHhZJ4nOJV9X8QmH1RDJaWDmI3qJYfySytkoIKnT0wXxRgrimYZxs4qxf5Klm3N%2BYx15huNuUCvgXbyBObxxc8sPlQ1FsoYOA2uO20s3HIzp2FwrbonwVQoVFsV1yFxoGkuDxkBZTGkkKVZVlSMq6g4Ke2hLE%2BXjo%2FdunqJhEkMBuPVpoJ5trTj0dgipTEEX47IPuIF25DZAcazbdXT7VUsUrb2Se7UdEiiO5ilezaW1jq8ekgTBY1y97jvuwvNIgWvd2KGxkBy%2BVyi8nSUzsCBVuUy48LjGOiorBGvPFTp5jnbw4ZFS8qWLY4H8bpMN35WC3YQkhluTIUz9DU%2F3%2FT%2BPJ%2B0%2Fgb)

**Comment by Domniq** [comment] 2024-01-20 09:02
@the-zimmermann it does not change anything

Here is smaller repo
[https://qwik.builder.io/playground/#v=1.4.0&f=7VfdbtMwFL7nKbwrJ9BESbv%2BpUsQg0kMMUCUu2lCTu2sYd1Stenaquq7c44dx0nLVqZpF0jsoosT%2B%2Fx%2B55zPFdA0%2B9VMycyooduogKFhZrF6xFksn2S%2FewxhRIdEiv4GU%2FQ9APgaKh4mGIPoYFxSHhRUoQErbGJ6DdEvJTwK0oJVSNYRGr6wgSpGbdBSgj3tl1fbCHOB50FCZedlEcCNNI02e8xrim7bafW8nnPMOm2HtZKR0%2B96Xr%2FJRZ%2F3m7RRGE7PVmO2mOeUbNGbp4nxjZhTlsMYX%2B%2BLYX4cd0Wv5TDRYs5x1xcO8%2BLEGfkMFHCv0%2FHbRsz59V2KoN%2BX042Pk5bf405vFPvOMW8nTr%2BfMMdvenHcafdaSRwbOcPFfCru5lVJV%2FC7bZANF2IayJnXAIgzqLt7OIFrbBCkzE7Ki9QoVqcyHFmUFrseKA%2BgoJqgUeAyUxhAAUkmYjUgvyDOabJ2cBYBIAA1U6A9TizypRB3A%2BBEK2eZ8nwckLbnTVcDuq3UCnLbcgXrVBJIBGpIsb9SsDikjPOfGANKQPNIjDNEeEg1kGhZbaocJU829HCjIPqOc0uC095G8FzyaWOMZNpPtU3wNH%2B%2BcUN2L5R1DZAKFuKLAybqRQkped41ReQCH7asYr1GPTXnyI1Yh7o6127Kty%2BSY1A2LQTTUTbJZgGgjA%2FIaDGb40LSKjEb0L2gfBe3mQlLxVCIT81uHIWP6bueSTMPaxxKdl2GrMiF0YV5rmurZcTGVqltiE4VRwWKBfW4AKJ5EkfSF8hrBNSMfBp%2B%2FeKqmQfRLcBZkX6CN7RoI7epSjXbwAr5dWewyDIuB%2B%2BOO%2FvtFx0Mimmjm4GazKpdSDIbAvlUvMkFmno2Efh4uj7nVgX8Njr08cfFZ3kFLDaBMVKEC5wN2HhocohvVcdJ%2Bf7XlOPJ6jVS75JkoOphWTcBOTRoXt5ZdCchlnHZLe4AEfGUJq1rtVqBqt2CRa8JgYsgsdQ2HRGSJXhEy1BqKuEiYRiWkTS7yomqAg4ajWlKV22PHA5aivkew0C50UuIvvqV%2F3cdgPNgJu7dQp5eqetHmaxqPf9tulSelEvo9NFSknYX4pOks1uLfsjIOluQJYPbY55Ba0EdcNmDssML11tq29JUNdlUkv5g9l7vTNIJ9Ih6%2B6yF6kiGfBeQ5ZQ57OBTsFdOwOdD7%2BFuQEK5rcQYhN%2B6YPnYTSZZNlOPeD%2FPbqFbviaW76k%2F4hD1SN4Q37bxVy5tN9eU3tbER1EZY%2BYhOF26LvS%2B%2BmszC64ULGs9hiLllfgj%2Fy9G%2F97F6Dc](url)

Here is video for you to see what's wrong
https://www.youtube.com/watch?v=curY0UAvcLg

**Comment by gioboa** [comment] 2024-03-05 17:15
It's really strange because I can't reproduce the problem constantly. I'll add a specific test in the Qwik v2 test just in case.

**Comment by gioboa** [comment] 2024-03-05 21:26
This example always fails :eyes: 

```
import { component$, useStore } from '@builder.io/qwik';

export default component$(() => {
  const store = useStore<{ users: { name: string }[] }>(
    { users: [{ name: 'Misko' }, { name: 'Giorgio' }] },
    { deep: true, reactive: true }
  );

  return (
    <>
      {store.users.map((user, key) => (
        <div key={key}>
          <div
            onClick$={() => {
              store.users = store.users.map(({ name }: { name: string }) => ({
                name: name === user.name ? name + '!' : name,
              }));
            }}
          >
            {user.name}
          </div>
        </div>
      ))}
      <span>{JSON.stringify(store)}</span>
    </>
  );
});
```

**Comment by gioboa** [comment] 2024-03-05 22:18
You found a workaround and that's okayish but with Qwik v2 it's working fine.
@Domniq thanks for opening this issue because it helps us to improve the codebase.

**Comment by Domniq** [comment] 2024-03-06 06:47
> You found a workaround and that's okayish but with Qwik v2 it's working fine. @Domniq thanks for opening this issue because it helps us to improve the codebase.

In most cases that workaround does the job well, sometimes it does not and i have to press button twice in order to "refresh" (switch tabs that filters "store" by status (int), stored array Type has 7 fields with various types)

Qwik v2 - you mean upcoming major update?

**Comment by gioboa** [comment] 2024-03-06 06:56
Yep, the new version of the rendering engine. This change will not affect final users, you can check the `build/v2` branch if you are curious.

**Comment by Domniq** [comment] 2024-03-06 08:27
Great news! :)

**Comment by mhevery** [comment] 2024-03-27 19:21
ROOT CAUSE ANALYSIS: This is a bug in Optimizer. The optimizer incorrectly marks the `onClick` listener as 'const'/'immutable'. Because it is const, the QRL associated with the click handler always points to the original object, and it is not updated.

**Comment by wmertens** [comment] 2024-03-27 19:36
@mhevery so this is also a problem in V2?

**Comment by jahwin** [comment] 2024-07-30 03:08
Hey @mhevery and @gioboa, 

I encountered the same issue. When running this code:

```javascript
import { component$, useStore } from '@builder.io/qwik';

export default component$(() => {
  const tasks = useStore<{ label: string; prio: number }[]>([]);

  return (
    <>
      <div>
        <p>
          <button
            onClick$={() => {
              tasks.push({ label: 'New Task' + tasks.length, prio: 1 });
            }}
          >
            Add new Task
          </button>
        </p>
        <ul>
          {tasks.map((task, index) => (
            <li key={index} class="flex">
              <span>{task.label}</span>
              <span>=====</span>
              <button
                onClick$={() => {
                  tasks.splice(index, 1);
                }}
              >
                Remove
              </button>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
});
```

the removal of elements is not working.

I tested this on versions from 1.0.0 to 1.2.14, and it worked fine. However, from version 1.3.0 to 1.7.2, it's not working.

**Comment by wmertens** [comment] 2024-07-30 07:33
It doesn't seem to be the optimizer, the code and html between versions remains the same. Something in 1.3 incorrectly removes nodes.

Here's an [illustration of the bug](https://qwik.dev/playground/#f=7VbBDoIwDP2VxYOOQFCuIib%2BglfjxTijEZUEMRqyf7ddYSsEjMaTiTuN0XWv7fZe%2BaWZRDYefmsCq7k0I7b69ipRXoCpSDMS51pOPPv%2FCiSaVz%2BN6pckJdOqn4jFUT2mtdTo1XouV2uIrD%2FD0MXgnqSsjw7hIRdKs8Rlbo5ZNe0OWxFO8UsXDx8GdZgV%2BV5avCPgKIGaMBJ%2BZUDEHFAIkcAnxL1ozT45JCEW263ROPTHsda92Yf4m6nw%2Ff6Dl5Xly0OREdxHkXIXJYUOHZKUOA1IfwwMKpXdmB6oUGgWwkxTq5kMdqm6D5q4wBzbyDkZm5Tr2dgsddoNz5s8i3ssOjL2TtVxUHR5BoZKmsgCEbXqiqNRWxxtEJjq0%2BWm2tg6Koyr6YGveJ5zPxu7AlAP3%2BIAL%2F7z9u%2Fx9hM):
- add a few tasks
- remove one in the middle
- notice that the one at the end seems to have been removed
- click the rerender button
- notice that the one in the middle was actually removed

**Comment by jahwin** [comment] 2024-08-01 15:35
I have continued testing and would like to update you on my findings. In a previous message, I mentioned that versions from 1.0.0 to 1.2.14 worked fine, but versions 1.3.0 to 1.7.2 did not. However, I have discovered that even in versions 1.0.0 to 1.2.14, including a component reintroduces the issue.

Here are the steps to reproduce the problem:
1. Add a few tasks.
2. Remove one task in the middle.
3. Notice that the task at the end appears to have been removed.
4. Click the rerender button.
5. Observe that the task in the middle was actually removed.

Below is the relevant code snippet:

```javascript
import { component$, useStore, useSignal } from '@builder.io/qwik';

export const TaskItem = component$((props: { name: string }) => {
  return <p>Hello {props.name}</p>;
});

export const Counter = component$(() => {
  const rerender = useSignal(0);
  const tasks = useStore<{ label: string; key: number }[]>([]);

  return (
    <>
      <div key={rerender.value}>
        <p>
          <button
            onClick$={() => {
              tasks.push({ label: 'New Task' + tasks.length, key: 1 });
            }}
          >
            Add new Task
          </button>
          <button
            onClick$={() => rerender.value++}
          >
            Rerender
          </button>
        </p>
        <ul>
          {tasks.map((task, index) => (
            <li key={task.key} class="flex">
            <TaskItem name={task.label} /> 
             {/* <span>{task.label}</span> */}
              <span>&nbsp;</span>
              <button
                onClick$={() => {
                  tasks.splice(index, 1);
                }}
              >
                Remove
              </button>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
});
```

@mhevery , @wmertens , @gioboa , could you please address this issue in the next release (version 1.7.4)? We have two significant projects built using Qwik, and switching frameworks is not a feasible option for us. Your prompt attention to this matter would be greatly appreciated. Thank you.

**Comment by wmertens** [comment] 2024-11-01 11:56
This is all fixed in v2, including the shorter repro I linked here https://github.com/QwikDev/qwik/issues/5662#issuecomment-2257671646

**Closed by wmertens** 2024-11-01 11:56 UTC
Labels: TYPE: bug, COMP: runtime, VERSION: upcoming major
