### ISSUE TITLE
[🐞] Version 1.5.3 build is broken: Cannot load native addon because loading addons is disabled

### ISSUE THREAD

**Issue by ohkimur** [QwikDev/qwik#6223] opened 2024-05-04 22:18 UTC
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

Starting with v1.5.3 the vite build fails. This fails in a few different environments, including the official `vite` template for `qwik`. Check it out [here](https://vitejs.dev/guide/).

Also, starting with this version, `qwik` doesn't respect custom rollup configs from vite properly, including custom `dir`, and `entryFileName` options.

**NOTE**: I'm working on a very big design system that supports all the major frameworks including `qwik`. For each one of them I build to `dist`. It would be great to be able to keep doing this for qwik.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zyuten?file=package.json

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 8.46 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.2 - ~/.nvm/versions/node/v21.7.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.2/bin/npm
    pnpm: 9.0.6 - ~/Library/pnpm/pnpm
    bun: 1.0.35 - ~/.bun/bin/bun
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 17.4.1
```

**Comment by PatrickJS** [comment] 2024-05-05 02:43
it might have been caused by 
https://github.com/QwikDev/qwik/pull/6178
or 
https://github.com/QwikDev/qwik/pull/6162

what do you think @wmertens

**Comment by PatrickJS** [comment] 2024-05-06 00:16
@ohkimur can you stay on 1.5.2 until we fix it

**Comment by PatrickJS** [comment] 2024-05-10 16:01
csr: true will be fixed in next release https://github.com/QwikDev/qwik/pull/6292

**Comment by wmertens** [comment] 2024-05-11 06:30
Ah and the dlopen issue is separate because now we ship a binary from Linux and it tries to use it in stackblitz.

So we need to be more careful about that.

**Comment by JerryWu1234** [comment] 2024-05-19 03:09
What can I do here ?

**Comment by PatrickJS** [comment] 2024-05-20 04:51
@wmertens you can outline what @JerryWu1234 can do 🙌

**Comment by ohkimur** [comment] 2024-05-28 19:40
@PatrickJS Do we have any update on this topic? I'm wondering if there's something I could help with. I see the [vite-demo](https://stackblitz.com/edit/vitejs-vite-xg3cr5?file=index.html&terminal=dev) still is failing to compile. The same happens still when I update to `v1.5.5`.

**Comment by PatrickJS** [comment] 2024-05-28 19:56
@wmertens is the only one with enough context on what to fix here

**Comment by wmertens** [comment] 2024-05-28 21:26
This is a cosmetic error. It shows that and then it uses wasm instead. I have a fix already but it's in a PR that's blocked right now, I'll add it separately when I get a chance.

**Comment by ohkimur** [comment] 2024-05-28 21:46
@wmertens Can you mention me in the PR? I'd like to take a look and understand the problem deeper if possible.

**Comment by wmertens** [comment] 2024-05-28 21:55
@ohkimur it's this commit https://github.com/QwikDev/qwik/pull/6326/commits/2b5384c66306f435c92bd8918d1d2f2b8f0cdfdf

**Comment by shairez** [comment] 2024-06-11 19:46
@wmertens did you have a chance to look at this yet?

**Comment by wmertens** [comment] 2024-06-18 19:08
Sorry it wasn't a fix really, it is just a less ominous message.

The webcontainer looks like Linux so it tries to load the Linux binary optimizer. 

It fails and then it falls back to wasm.

At best we can try to detect web containers

**Comment by wmertens** [comment] 2024-06-18 19:29
I'm going to close this, but if someone knows of a way to detect webcontainers I'm all ears.

**Closed by wmertens** 2024-06-18 19:29 UTC
Labels: TYPE: bug, COMP: optimizer, P4: urgent, WAITING FOR: team, STATUS-2: requires discussion
