### ISSUE TITLE
[🐞] Qwik doesnt check `if-statements` before running child useComputed$ or useTask$

### ISSUE THREAD

**Issue by DustinJSilk** [QwikDev/qwik#4332] opened 2023-05-25 11:14 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

The following code causes Qwik to crash when the button is clicked. Conditionals aren't checked before child component tasks are run when using Signals.

```tsx
import { component$, useSignal, useTask$ } from "@builder.io/qwik";

// A useTask$ in a child components circumvents the parent components conditional checks
const Child = component$((props: { val: string }) => {
  useTask$(({ track }) => {
    track(() => props.val)
  });
  return <>{props.val}</>;
});

export default component$(() => {
  const sig = useSignal<{ data: string } | undefined>({ data: '' });

  return (
    <>
      <button onClick$={() => (sig.value = sig.value ? undefined : { data: '' })}>Toggle</button>

      {/* ERROR: cannot read data of undefined */}
      {sig.value && <Child val={sig.value.data} />}
    </>
  );
});
```

### Reproduction

https://github.com/DustinJSilk/qwik-issue-rendering/blob/main/src/routes/index.tsx

### Steps to reproduce

Run the app
Click the button

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 116.35 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Safari: 15.1
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

**Comment by DustinJSilk** [comment] 2023-05-25 12:15
If we update the child component to this, we see that the error is fixed but the useComputed$ still runs when it shouldnt and we go against the type system as someValue should not be undefined:

```tsx
const Child = component$((props: { someValue: number[] }) => {
  const max = useComputed$(() => {
    console.log("Computing");
    return Math.max(...(props.someValue ?? [1, 2]));
  });
  return <div>{max.value}</div>;
});
```

**Comment by DustinJSilk** [comment] 2023-05-30 11:39
@manucorporat  sorry to be a pain, any chance you could take a look at this or know a work around? 🙏 

Unfortunately i dont know qwik well enough to fix it myself (tho i have tried!) and I haven't found a way around it yet either.

**Comment by DustinJSilk** [comment] 2023-06-05 10:36
@manucorporat Ive added an e2e test to the [reproduction repository here](https://github.com/DustinJSilk/qwik-issue-rendering/blob/main/src/routes/test/index.tsx), hopefully that helps simulating and testing a fix for this issue.

Let me know if there's anything I can do to help here!

**Comment by DustinJSilk** [comment] 2023-06-07 08:48
The issue also occurs when using a `useTask$`. You can see the console.log prints `undefined` when it shouldnt run at all. Swapping undefined for null doesn't help and I havent found a way around it yet.

```tsx
import { component$, useSignal, useTask$ } from "@builder.io/qwik";

const Child = component$((props: { someValue: number[] }) => {
  const data = useSignal(props.someValue);
  useTask$(({ track }) => {
    track(() => props.someValue);
    data.value = props.someValue;
    console.log(props.someValue);
  });
  return <div>{data.value}</div>;
});

export default component$(() => {
  const data = useSignal<number[] | undefined>([1, 2, 3, 4, 5]);

  return (
    <>
      <div>{data.value && <Child someValue={data.value} />}</div>
      <button onClick$={() => (data.value = undefined)}>Click me</button>
    </>
  );
});
```

**Comment by DustinJSilk** [comment] 2023-10-16 11:07
I keep running into this issue, am I doing something wrong here?

```ts
import { component$, useSignal, useTask$ } from "@builder.io/qwik";

const Child = component$((props: { val: string }) => {
  useTask$(({ track }) => {
    track(() => props.val)
  });
  return <>{props.val}</>;
});

export default component$(() => {
  const sig = useSignal<{ data: string }>();

  return (
    <>
      <button
        onClick$={() => (sig.value = sig.value ? undefined : { data: "" })}
      >
        Toggle
      </button>
      {sig.value && <Child val={sig.value.data} />}
    </>
  );
});

```

**Comment by wmertens** [comment] 2023-10-16 19:59
@cmbartschat I don't understand, what are you demostrating? You're throwing on purpose there?

The "problem" is that the `{sig.value && ` runs at a different time than the updating of the passed signal prop function `sig.value.data`.

I don't consider this a bug per se, it's more of an unexpected result of splitting your app in tiny parts that update via signals.

**Comment by DustinJSilk** [comment] 2023-10-16 20:52
Why wouldn’t it be a bug? Signals are unavoidable and so is splitting an app into smaller parts. So surely it’s a bug if the result is unexpected? Please let me know if I’m missing something fundamental here :)

**Comment by wmertens** [comment] 2023-10-16 21:15
Hmm.

So a solution would be that the optimizer keeps track of statements that cause a signal to be forwarded, converting then to a filter function, right? And it should first call the filter function and only then the signal function?

I wonder how deep this rabbit hole goes, what statements should be converted etc.

**Comment by DustinJSilk** [comment] 2023-10-16 21:27
To be honest, I don’t know what a solution would look like, I don’t know the inner workings of qwik or what the various trade offs would be.

Do you know if any other framework has solved or suffers from the same issue?

**Comment by wmertens** [comment] 2023-10-16 22:02
I don't know of any other framework that converts values into signals and re-renders asynchronously thanks to that.

The workaround is to add a ? after signal.value, which the linter doesn't complain about because it doesn't know that it will become a separate function called separately.

**Comment by DustinJSilk** [comment] 2023-10-17 05:44
Yep so the only real work around is to avoid the conditional completely, it kind of is bananas lol

**Comment by cmbartschat** [comment] 2023-10-17 06:36
Sorry for the cryptic example!

What I was trying to show is that based on the contract of the `Child` component, as long as you don't pass "bananas", everything is fine. And naively, it does seem like we're following that contract in that example.

 Here's [another example](https://qwik.builder.io/playground/#v=1.2.13&f=7VfBSsNAEP2VtQjZQAmWIkLJtjdP0oveJdhIA5WKjVJI8%2B%2B%2BmdnN7sY2FS8i2ENJd2feZmZ25r2Gl%2Bb6JqiUr%2F%2B441x%2B4rnGT921HrxXXGLJ6B1GzxsmneEU0MZMJSIMEiygo96xIgtItrgumUaOugrDBK6yQK5R9gVC6g4EH1regJ4YeNY7p51r1jeuXp1Q0E%2F1vquiUviVsQywXcJOmQVNxSSQIcn99qWs16SEWBFUHyBjZo%2FC8yX7JuMYK%2BMQs3p7W%2B3LlZ6mBN7Sl2tK0mdCx5imo2bYux0pLQemouzQwb2sSc3OZC0u7C9kzerK4ay9FitinFpf%2FShtgTvlTY48krfB2WnFLoth07WUbtzdTRJ6LxhCHxEXggVLMLxaoz9LzEWKdybbZ6GmDkssRSqIqeci%2F2rOrthJE8BSHhAqgCULjKdU9az0RbCsDgdrnFW7ZbHUDiSV0Uofm%2Bqm1%2FI4Tw4e%2B9b3uC07t6rcIAmnkOwE%2BIrUhWJhpOrB4LUzN19P5g8QgMCja%2BS6EJN1MpeA84r%2FTDCuaYI3bKH8%2BY%2FGpWn0I7iM9bIkNYrE2C0XWEtjmbEbqYxsLDKed8YYH9dC5dHwsvfSRI6Ep2j4bTYS7UlYl3jARt39HViwRvpP83%2BU5j8B) to show the sorts of things a real world example might try to do.

I would describe the problem simply that [type narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) does not work on signals.

No matter what we write in the render logic, at runtime, the signal is not type narrowed, because it gets flushed through before the narrowing logic can run. 

This can be a source of bugs that Typescript cannot detect.

**Comment by wmertens** [comment] 2023-10-17 08:32
Ok your real-world example is convincing. It's easy to see that this could lead to frustrating debug sessions.

So indeed I think the proper solution is that the optimizer supports filter functions before updating prop signals. But I don't think that's trivial to add.

**Comment by DustinJSilk** [comment] 2023-10-17 11:07
@manucorporat @mhevery is there anything we can do about this issue?

**Comment by mhevery** [comment] 2023-10-19 19:13
Yeah, this is a hard one. I need to dig deeper into this to see what a fix could be.

The issue is that the order in which we process events is not preserved.

**Comment by wmertens** [comment] 2023-10-19 19:31
Does this happen in other situations than when signals are proxied in props by the optimizer? If not, I believe a filter function should work

**Comment by mhevery** [comment] 2023-10-19 19:49
> Does this happen in other situations than when signals are proxied in props by the optimizer? If not, I believe a filter function should work

I have seen other issues on this topic, but I can't find them now.

The issue is that the effects should run in the correct order and then prune its children. I think the code should work as written, but we don't process the effects in the correct order which results in this issue. Happy to have a chat if you want to dig deeper into this.

**Comment by DustinJSilk** [comment] 2023-10-21 10:18
Thanks @mhevery and @wmertens i appreciate you guys taking the time to think about this one!

**Comment by brandonpittman** [comment] 2023-12-26 03:03
I'm getting a similar issue where due to conditional rendering I'm getting two of the same component in the DOM—one hidden and one not hidden. Both components' `useTask$` calls are being fired when the signal value they're tracking changes. Since I'm updating a store value in that task, a double store value change happens.

**Comment by wmertens** [comment] 2023-12-26 04:27
@brandonpittman that's by design, because children and parents render independently.

So if you render items in slots, they will always render and update even when the slot is not visible.

**Comment by brandonpittman** [comment] 2023-12-26 05:23
@wmertens 

> So if you render items in slots, they will always render and update even when the slot is not visible.

That was the conclusion I came to. I created a `<Show>` component similar to Solid.js' but it's causing more trouble than it's worth. I wanted to embed the show/hide logic inside child components, but it seems like I can't do that without unintended consequences.

**Comment by wmertens** [comment] 2024-01-19 16:12
> If the projected content isn't displayed at render, it'll go into a q:template. And if that project content is subject to dynamic updates that change the structure of the slotted HTML, it's possible the initial server q:template can exist in the DOM next to a dynamically created element that gets placed in the slot?

Uhm, yes? Not quite sure what you mean, a playground repro would be nice.

**Comment by DustinJSilk** [comment] 2024-05-20 11:58
Looks like this will be fixed in V2 🫨❤️

**Comment by tri2820** [comment] 2024-08-19 04:00
This simple [example](https://qwik.dev/playground/#f=7VY9a8MwEN37K0QWpcR4bTEkHTJ1KaV0L0ojt4baBrWhBKP%2F3nd3smSZULIGkoBJfKf7eLqPNyma%2B7uTRVOk7cs%2FYzH%2FW018sc%2FW0dBZc8Z1475%2F3mgsVYEMFPTWtM3XMXsNmG8ENTnP6W%2BN28PQtCoD%2FwBfYLVqdOcjyGKlxmRkBzifNaPcBpspxUaZglQrpfFdzeQpXOCXGoK4EcdZqEdlWjVEpyXmxMF6oU%2FSJ2e1msQubiXwwIAky82SlHJU9atrNIE6g1U%2FfRyOttOQkPs8aqkI4XSJygwpEPqE7DkVCgZtUmPe71ns%2FebFtj1WlKhFhshSfpy08yAyeJ%2Ffs6ith6m6Ry2rajwCDsFL47ehrWdpj%2B1G%2FgF6s7PvBojl5cq6nwZxJiOLrek6tCZmKdzipi24HXZOX6ck1ZKkRF51QlvfLhQWbe%2FGHAhLrDDsW4TV9RGLiLHHM%2Fy9DsvLHJZ%2F) shows how this bug breaks code that appears to work in Qwik. TypeScript does not show any warnings or errors either. 

For `useTask$`, when I switch to `useVisibleTask$` it works (because all input signals are correctly their type at that point).
For `useComputed$`, could the solution be to allow it to run after rendering, like `useVisibleTask$`?
```
const _  = useVisibleComputed$(() => {

})
```

This way the computation is not async anymore, but at least it's a safe alternative to circumvent situation like this.

**Comment by wmertens** [comment] 2024-11-01 12:06
This bug is still present in v2, likely because the qwikloader doesn't add events to the scheduler yet

https://qwikdev-build-v2.qwik-8nx.pages.dev/playground/#f=7VZNa8JAEL37K6Ze1mLIsZSA9tBTL6WU3stqNhIwClEPEve%2FO1%2FuriGIV0EFMZud2Z03M29eUjTvb4NFk8Xpy39DMd%2BsJk7sj2uJdGYccVW3u%2F0%2F0VKhYiCjVdvU6%2BPVMsI8EtTEnsP%2FtG2JjtKqVP2BeoG3FZfjfABZvFTIjHwA2l81Y8wGQF3B5IU95uJOCoM%2BqYwwdAGyhqVFhimZ%2BYnhUlPzqpaa5PHClmNe8vyry6lJHtGBKRj8TnvvI07og7otdiMJMwYpgy%2BwDXQh4hxJ6uC8aDdp0rv6XICTowU1lV8K8Qlw1roKKb%2BcTwSnNL3mr60NZbeXX%2FO9OhzdxgxGIKUp4jJqqi5NEuiVJCy62OUWgq6f%2F7pmi7NStgWpOuLXgz4%2BYr%2F0q032zbp0v8eOgiLa0MVxcOGUxQm22YaDQ0CUcX18UuRjUuQZ

**Comment by berli888** [comment] 2024-11-25 00:57
how is this a bug ? according to documentation, props are immutable.
https://qwik.dev/docs/components/overview/#props

> Props are shallowly immutable, meaning primitive data types (strings, numbers, booleans) cannot be changed once passed. However, internal elements of reference types (objects, arrays, functions) can be changed despite the reference itself being immutable.

The only way I found to overcome this limitation is to pass the signal directly and run again the condition into the child component.

**Comment by Varixo** [comment] 2024-12-20 12:30
should be fixed by #7088 in v2

**Closed by Varixo** 2024-12-20 12:30 UTC
Labels: TYPE: bug, COMP: optimizer, VERSION: upcoming major

**Comment by DustinJSilk** [comment] 2024-12-20 12:38
You are a HERO @Varixo. I’ll start testing the alpha versions with my app

**Comment by ianlet** [comment] 2025-04-27 15:38
@Varixo do you think there could be a not too complicated way to backport the fix in v1? We're regularly hitting that bug and having to change our props to make them optional + add a lot of null checking everywhere is a bit of a pain.

We've just hit this again today when the user is trying to close one of our overlay panel:
![Image](https://github.com/user-attachments/assets/358c8551-03da-447b-9b8d-fe944329f4af)
