### ISSUE TITLE
[🐞]I get an error when I ran pnpm run build.full

### ISSUE THREAD

**Issue by JerryWu1234** [QwikDev/qwik#7199] opened 2024-12-27 06:26 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

![image](https://github.com/user-attachments/assets/769b76e9-38f2-409c-8d0f-033777c9b15b)

### Reproduction

qwik project

### System Info

```shell
mac 

  System:
    OS: macOS 14.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 291.14 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.8.3 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.2.0 - ~/Library/pnpm/pnpm
  Browsers:
    Edge: 131.0.2903.112
    Safari: 17.6
  npmPackages:
    undici: ^5.12.0 => 5.12.0 
    vite: ^2.9.5 => 2.9.15
```

**Comment by gioboa** [comment] 2024-12-27 08:47
Thanks for the feedback, it's duplicate of #7146 
I close it

**Closed by gioboa** 2024-12-27 08:47 UTC
Labels: TYPE: bug, STATUS-1: needs triage
