### ISSUE TITLE
[✨] `qwik new Button --barrel` to create `Button/index.tsx` instead of `Button/button.tsx`

### ISSUE THREAD

**Issue by p3yman** [QwikDev/qwik#4933] opened 2023-08-14 12:51 UTC
### Which component is affected?

Starters / CLI

### Describe the bug

In [Utilities section](https://qwik.builder.io/docs/project-structure/#utilities) on project structure page, it says by running this command:
```tsx
pnpm qwik new Button
```
it'll create this file:
```tsx
├── src
│   ├── components
│   │       Button
│   │       └── index.tsx  
```
But in reality, it creates `Button/button.tsx`.

I'm creating a bug for it as I think the `Button/index.tsx` would be a better pattern than the `Button/button.tsx`.

### Reproduction

https://github.com/p3yman/qwik-cli-new-component-bug

### Steps to reproduce

Run `yarn qwik new Button`

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 111.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.0 => 4.4.0
```

**Comment by shairez** [comment] 2023-08-14 15:08
Hi @p3yman 
This is not a bug but a feature request

Not everyone likes the `index.tsx` pattern as it leads to lots and lots of files with the same name.

So it might be an optional `--barrel` param you can pass to the CLI to generate an index instead of the component name. 

It looks like a PR the community (or you) could create and we'll review

Thanks!

**Comment by p3yman** [comment] 2023-08-14 19:12
Awesome, absolutely!

**Comment by gioboa** [comment] 2024-06-17 09:51
Closed by https://github.com/QwikDev/qwik/pull/5202

**Closed by gioboa** 2024-06-17 09:51 UTC
Labels: TYPE: enhancement, COMMUNITY: PR is welcomed
