### ISSUE TITLE
[🐞] Server crashes when accessing URL with double slashes (//)

### ISSUE THREAD

**Issue by canaria-computer** [QwikDev/qwik#6840] opened 2024-08-30 07:58 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I am using the Qwik framework, and I have encountered an issue where accessing the URL http://localhost:5173// (http://\<origin\>\/\/) causes the server to crash.

### Reproduction

https://stackblitz.com/github/QwikDev/qwik-new-for-stackblitz?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Typically, URLs containing double slashes or relative paths should return a 400 Bad Request or a 404 Not Found response instead of crashing the server.

1. Set up a Qwik application.
2. Start the development server.
3. Access the URL [http://localhost:5173//](http://localhost:5173//).

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 2.69 GB / 15.66 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.0 - C:\ProgramData\chocolatey\bin\pnpm.EXE
    bun: 1.1.23 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.98)
  npmPackages:
    @builder.io/qwik: ^1.8.0 => 1.8.0
    @builder.io/qwik-city: ^1.8.0 => 1.8.0
    typescript: 5.4.5 => 5.4.5
    undici: * => 6.19.8
    vite: 5.3.5 => 5.3.5
```

**Comment by JerryWu1234** [comment] 2024-08-30 09:20
I will pick up this

**Comment by gioboa** [comment] 2024-08-30 10:48
Thanks @canaria-computer for reporting your feedback and @JerryWu1234 for your help.
It's a duplicate of #6004 so I close this one. Let's continue there.

**Closed by gioboa** 2024-08-30 10:48 UTC
Labels: TYPE: bug, STATUS-1: needs triage
