### ISSUE TITLE
[✨] stopPropagation:{eventName}

### ISSUE THREAD

**Issue by eonicum** [QwikDev/qwik#5322] opened 2023-10-17 13:53 UTC
### Is your feature request related to a problem?

I want to implement a card and like button positioned absolute on top of it. When a user clicks on the card body, a details drawer appears on the screen. But if the user clicks the button, a backend request is called.

https://qwik.builder.io/playground/#v=1.2.13&f=7VY9C8IwEN39FUGH0q1FBEnQxVVwcBSHlgZbtDSm9QOk%2F913%2BWg7CNJRkA4lcORyd%2B%2FeewPQLOLlaNBMbHlgHaNgKDFQVV1QazkxFhbnLgXpjgJZcJYSmQrwZdbknM2jSD0F1KA45U137NmcsxnoDB9S2UTWe3zIlaRgSeyYYNpeFmtZ4q4K8aU9mfeOQLmbDWxPL%2FEvGzV0FsFhk2gIPAUc2U6B3TMJOrzULNPJA4gNW%2B8qfJ%2FafmamoC8JtsVZutJ9nj2gajpFfy2vN6hbEGJWtFGrqQ2e%2BryDtrVruq1zcQ4Q5O0cJv6L%2FJOL%2FAY

### Describe the solution you'd like

I want to have stopPropagation:{eventName} attribute similar to preventDefault:{eventName}.

### Describe alternatives you've considered

1. useVisibleTask$ - Doesn't work :( Why? https://qwik.builder.io/playground/#v=1.2.13&f=7ZbBSsNAEIbvPsVQDxuhhIqgkGAv0psgeBUPKTu1wZYuaa2C5N39ZybJrlHEq%2BAW2qTZzOwMM9%2F8SdFcXQ7hpEUzjdNXL1O8%2FVhQJxY6iKTTDeG7sNvXkvZCaIamOnIpMykAJAUtBbQlWOoP64IuZrPwVmJS1E%2Frw3AbSV%2FQKVCHD1yZI9Ml3%2FiqliAo%2Bq%2BkxoydN7yFrR32b%2B1Oz%2FubDjBX4Aca%2Bp5XcBS1yWLD0tXzDKkl7B3PgmiFqF6hHHsrOVjywlaKskYP8sr7xRGWZXQxMJs5ZaybUsbyf2JXVqp73MNt%2FcxdbgzNj6J1AkACnaVgc3Lebqm9fLRBA9Ilba6%2F%2BJbrL5UMkRgF0btF%2FPk8N1UDOWQHuQuYhZ4xPDZ78k31iv4%2Ba3sN1ldOGyvcwlCZOCSpVYpcT%2BzhpH87KYd2LkkYlGvXBKJnuz74h9efhNcH
2. [Event target](https://qwik.builder.io/docs/components/events/#event-target) - Current solution https://qwik.builder.io/playground/#v=1.2.13&f=7VZLa8JAEL73V0ztIS1IsRSkZEkvvfRQ6KG9iYdoVg2%2B4hofIPnvfjOTlw%2FEq2ACG5bs7MzufPN9UwNNu%2F1xDjRNuoybBz0hiEdEDKf0kvky5tv1mbRQO2trWHoS8IVPPeZTA8qM0pFP761WsjUQhHg4SstpReg%2BPYHR8MKVOtL244yvsAeiRJkZcrrZm7NT7DXH%2BqnOJN5rgK6u%2BqGLRNu%2FoQbMJwFhkV1jcZP6K%2FDsLP0XlSwNieIBPR%2F8o8cgIDF6VUlVzPGjKDAyy2SUod64eJ0vRKGk2qXfBOIRWbDtZEmRCzcoCCQS1jye4AotW9We7I6PkxXNTpG7rIKSXHLNVq7mMK6feGzzbBTh%2FaGAJHn8dXaxguZ6L4AP13nQ0MWNwm0tk9kn71b2ljlMuePMkXqnl5uklz0

**Comment by mhevery** [comment] 2023-10-19 19:34
I like that idea. Could I encourage you to create a PR with this feature?

**Comment by eonicum** [comment] 2023-10-20 17:47
Sure, I can work on the PR

**Comment by gioboa** [comment] 2023-10-21 15:00
Thanks @eonicum 👏

**Comment by mhevery** [comment] 2023-10-21 16:41
You rock!

**Comment by sarat1669** [comment] 2024-04-15 01:51
@mhevery can we reopen this? `e.stopPropagation` doesn't work. #5545 doesn't account for stopPropagation.

**Comment by PatrickJS** [comment] 2024-04-15 04:19
yeah you're looking for a declarative way of doing this rather than sync$

**Comment by sarat1669** [comment] 2024-04-15 07:06
Tried `sync$` as well. StopPropagation doesn't work in all the cases.
Reproduction: https://codesandbox.io/p/sandbox/sleepy-sunset-qkjdmh

**Comment by wmertens** [comment] 2024-04-15 07:16
@sarat1669 sync$ will 100% work. Can you explain when it doesn't work?

**Comment by sarat1669** [comment] 2024-04-15 07:39
@wmertens, 
<img width="619" alt="Screenshot 2024-04-15 at 13 08 15" src="https://github.com/QwikDev/qwik/assets/11179580/ea42512f-7242-459e-ac22-e9f60a59af74">

I have shared a codesandbox link to a re-produceable link of this issue.
Clicking on`R Left Left` logs both `R Left Left` and `RLeft` which is it's parent.

**Comment by wmertens** [comment] 2024-04-15 08:27
@sarat1669 that sandbox behaves really weirdly for me. Can you reproduce it on https://qwik.dev/playground ?

**Comment by wmertens** [comment] 2024-04-15 08:29
@sarat1669 here's the original repro but with sync$ added https://qwik.dev/playground/#f=7Va7CsJAEOz9ikMLDYhEJE0ObWwFC0uxSMhhgoacl%2FgAyb87e5sXEgRLQVKEg%2BX2cTOz0wGN53l9oJkKIu9n7Ay4S4iPXWTodKyzPKEJ%2ByRc4M9NSVo%2FGprhi5A0VUI2oyL2xcJ19UNiKSTHuGiOraj7YgRVw4dUnIgtSE%2BuIIRYgmpSGL5sblSKuzLEp3yy9X4B9uqJ4H7aTf%2FkqK7BGO%2FXgcGep4CD2GqIfKSgiudcRCa4A7hOWZuLek5l%2B3S2oU4CO%2FPJRHE1agZ7osF9WCPWIke%2BZd8kJ1XNpS5iBzjbMdLfqMsVGxBVoA6i3XLI0cO6qs5QyxVd11i9CjVkACvg%2FNn%2Bk2x%2FAQ

**Comment by sarat1669** [comment] 2024-04-15 08:30
@wmertens , yes, it's the same
<img width="501" alt="Screenshot 2024-04-15 at 14 00 08" src="https://github.com/QwikDev/qwik/assets/11179580/454a2952-7efa-486d-a2c8-4b6d3d81fd3b">

**Comment by wmertens** [comment] 2024-04-15 08:38
@sarat1669 ah, the problem is that the stopPropagation needs to be called in each handler

https://qwik.dev/playground/#f=7VbNSgMxEH6VsIeyxbJ0QTwsBF9APIiepAd1Y%2B2lLuJBWPLufjPJTDbpViyehC79yU4m8%2FtNZqagubxaz6FmZah68YePdF%2BJelVmqSo9v33vHTyfwgnNFUSIjT0E8d0%2FhA7kjwQIs0d0JPZnYgkPSh76O5XW8M1nLdoxqb42VTt8Gdyhu948o1lVppuSth%2FO7auVihue%2Bh7J70y7FqL3caGdfnxUfo5NXTs1XB7XYKQYUK8YZ8L9gYjLpl8mjaefNtloQ26y0xmHhHR2O6nfBN8EJqNyi8%2BB8kLtD%2BVhFgsVkm00mHlq1sWuhLRF6DEEaMuyMK%2BpsqOsvNprR1n5hF6gdRkMCmNohC%2B%2BOdjukcwDsH2C%2BDuwEefPHv3Rl%2BWs1VSoudFqWJyQo2RwSQHWASyUKcA54peHo84wcFmNCFCXLaGNwZAAVxQOywxQ0Z0wddmScGFaYsxUUQzBmZlHt5%2BYGKPbGSmhhHrhNjfuVfjnz%2BTnDs6WAgohm%2BmOTy9KV9qMbXe77dsR48rz%2FI47dtI4GaAUIjvS7ynwicgpuxvAc%2B67%2F6%2FvfgM

**Comment by sarat1669** [comment] 2024-04-15 08:49
😯 Thanks. We may need to call this out in the documentation.

**Comment by PatrickJS** [comment] 2024-04-16 06:39
ok well this pr https://github.com/QwikDev/qwik/pull/6121 should bypass having to do it in each handler

**Comment by PatrickJS** [comment] 2024-04-16 06:56
oh well this was why.
![image](https://github.com/QwikDev/qwik/assets/1016365/73931c3b-db6a-46d7-ae69-70dff9954534)

https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation

it looks like stopImmediatePropagation only works correctly after the first click

https://qwik.dev/playground/#f=7VY9T8QwDP0rUYdTT5yq6wBDpYgZCTEgmNANQMvR5agQA1KV%2F86zEztNruVDTEhU95E6jmM7z3meguZ0ezaHmo2h6sUfPsK%2BkvUiP6Uij%2Fzqpe0Q%2BRROIFcIYTZwCPJ7uPUM5BYShN4jBBL4mVT8g5LH%2Fo1aq%2FjmsxZ0TFufm6Ie3g3u0L41DyCrwjRT0f616w7FRs0N922Lw29MvRWhc2GgTD%2FeqT7npiw7dVyerkJLMVyAT9oeoaFw0df4iwSpj3qgQ6%2B6oOHW0bnZjb4yYJJGiJLCKUo05ABmp6MHO58JAdWo2pIhL3kkskQxmdVKjSQTFTqkkvfiaPwhB6AyYGjKsjGnB2tHGTn1144ychHrwPbaO%2BSb1gB2fFNo3uDoj6D5BuH3oEman0f0y1jWs15TWadOq2Ohnw6WoSXlWnq80EkB%2FAHt3Eo1hmHO24gBDdkS4BgMEXNZmbFNDxWd8T2azQUnpibFZCvKITQT9%2BiuFBdDdhsjBReBL9rmsnsS%2Ffk16bqjtbmBzMhuOuPii8pVNuPbdb9%2FXnAuX8%2FvuJEnNMsApRTZkX5%2FAp%2BAnJwLAZ5%2Flv57LP0B

**Comment by PatrickJS** [comment] 2024-04-16 07:01
ok @wmertens the issue happens when the second event is async (not sync$) so likely an issue with how we're managing the event in qwikloader
 https://qwik.dev/playground/#f=7VZNS8NAEP0rSw42xTbYgyCBRTwK4kH0JD2oibWXWqQHIex%2F983MziS7af3Ak2Bp2s3u7Hztm30zBM3pmcUzRM3MUfXiD19lX816kZ9SkUd%2B%2Fdq0iHwIJ5ArJqE2cgjyu7kTBgoHEoTeIwYS%2BZlE5IOSh%2F3atFV883kPOibT565YbN8d7tB14x5BVoWrh1Ort7bdFDNTt31oGhx%2B7RYnOhlCHBD%2Fz0nrnGz4joZsTgWsFejuTSEnryxbi0w%2FbYWeY3sJwmnWiB2VjcZHbhqcTS8HvhTRAxJh2nuvxlBZzN4jo18pc0nXJEoqPBc71AQ6v7acpFmYTHNn9TBLS89eZ5eSNAXoOJky80TEi8J0R0emJFmo0G2VbIuDFcBE0DP4aEnOKhhIfKejYP76TkehrxvUyVQckgY4Fg6eFOa3gNEI5jtMfg%2FmJPl5RL%2BMhU5p7DVdEanT5ljszaNmSGnplwInOikUUqwcbstqxyXDZlSBhewdtDMYekhmJcs6BSq2Iv2ezyeO3YIEE1OUQ0gm7tG9qy7G7NZOa7OvC5V2V%2B2zyu%2Ffk%2B4b7c0VZEqWw5XQv9i8ze3x7Wa9ejngXL6f33G7DyibAUop8h39%2FgQ%2BETk5rwI8%2F4z%2F9xj%2FAw

**Comment by PatrickJS** [comment] 2024-04-16 18:23
check this out. this will work if you have sync$ at the end because of the order in things resolving
https://qwik.dev/playground/#f=7VbNSgNBDH6VsIeyxVIsIsji4AuIB9GT9KDuWnupRTwIy7y7XzKT7Mx0WxVPQpd2fzKZTJL5Ml9S0JyfXYyhZkZcvXjgp%2ByrWa%2FKXarKyG%2Fe2g6Rp3ACuUIIs5FDkN%2FNfWAgvydB6D1iIJGfWSVcKHms35i1uZx8zoGOeekrqhbbT8IZum7pCWRVUZOKVu9dt6lmZm772LbY%2FIYWpyr0Pr4Y0%2FcPpg82k%2FTUdWe%2B24jcujl6iy0KF31NOEiQ%2BkTJT4fVR8zQYQOUtTkcsiQg09D0jg6ny%2B%2BJ5BsXBgvLkCkFXW%2FraQaD5JnJFMVGk4kZyQbm6KBq8VY8CSAI16UAioecGPO28a7XN28Ru17f%2FFALwP40OBSa2lgM%2BOfQvQM0dqD7AeHPoMuahyP6YyzTUa%2B57HOnzbHYb0fL0NJyrsNe806hOGI1SKvVkJSBLKMGLGTHeBU4DXgpylBsBqjYSOjhXCk4oQUrZktxDqGZucdnqboYs9uQFuQAWtWm6%2B5F9cfn5PN25pYGCiPLdMQPHyY32Yhvt%2BvV6x7nyvnyjRM7oWEBKKfI9Xz%2FDXwickquBHiOLP7%2FWPwL

**Comment by PatrickJS** [comment] 2024-04-16 22:14
ok I got the fix for both stoppropagation attribute and sync$
https://github.com/QwikDev/qwik/pull/6123

**Closed** 2024-04-16 23:13 UTC
Labels: TYPE: enhancement, STATUS-1: needs triage
