### ISSUE TITLE
[🐞] Nested reactivity breaks inside `.map()`

### ISSUE THREAD

**Issue by samijaber** [QwikDev/qwik#5017] opened 2023-08-25 16:31 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

Nested access of deep recursive store isn't updating.

### Reproduction

https://github.com/samijaber/reactivity-bug-repro/blob/nested-reactivity-repro/src/routes/index.tsx

### Steps to reproduce

run https://github.com/samijaber/reactivity-bug-repro/blob/nested-reactivity-repro/src/routes/index.tsx

### System Info

```shell
N/A
```

**Comment by ulic75** [comment] 2023-08-25 17:30
Looks like maybe a dup of #5008?

**Comment by mhevery** [comment] 2023-08-25 17:56
> Looks like maybe a dup of #5008?

This example uses `() => ` so I don't think that is it.

But I do think it is a duplicate of #5001

**Comment by mhevery** [comment] 2023-08-28 21:35
https://github.com/BuilderIO/qwik/pull/5013 does not fix this issue so maybe it is not a duplicate of #5001...

**Comment by mhevery** [comment] 2023-08-28 22:48
I have a simpler repro:
```typescript
import { component$, useStore } from "@builder.io/qwik";

export const Child = component$<{ columns: string }>(({ columns }) => {
  return <div>Child: {columns}</div>;
});

export default component$(() => {
  const state = useStore([{ columns: "INITIAL" }]);
  return (
    <>
      <button onClick$={() => (state[0] = { columns: "UPDATE" })}>
        update!
      </button>
      <Child columns={state[0].columns} /> {/* <== Updates correctly */}
      {state.map((block, idx) => {
        return <Child columns={block.columns} key={idx} />;  {/* <== FAILs to update */}
      })}
    </>
  );
});
```

**Comment by PatrickJS** [comment] 2024-05-10 20:28
looks like it's going to be fixed in v2 with https://github.com/QwikDev/qwik/pull/5987/files

**Closed by PatrickJS** 2024-05-10 20:28 UTC
Labels: TYPE: bug, STATUS-1: needs triage
