### ISSUE TITLE
[🐞] Static assets not available via direct URL in dev mode

### ISSUE THREAD

**Issue by frammiie** [QwikDev/qwik#2660] opened 2023-01-17 16:21 UTC
### Which component is affected?

Qwik City (routing)

### Abstract
I've run into an issue where all public path files are inaccessible (result in 404 or hang)
with the default npm create qwik@latest template. This includes files such as
robots.txt, but favicon.svg and manifest.json seem to be working fine.

I've tried the different modes, and production and preview mode seem to result in the
public paths being accessible. But this isn't the case for the ssr and dev modes.

### Attempted Remedies

Files retrieved via relative URL in code, or in requests from pages work as expected.
For example

```css
@font-face {
  ...
  src: url(/assets/font-name.woff2);
}
```

Does not work, while the following does:

```css
@font-face {
    src: url('../public/assets/fonts/font-name.woff2');
}
```

As well as

```js
(await fetch('./hello.txt')).text(); 
 ```
 
 from within pages.

### Reproduction

https://stackblitz.com/edit/qwik-starter-rrx14g?file=src/routes/index.tsx

### Steps to reproduce

**Scenario**

1. Load the main page
2. Observe the text `Hello world!`, this means it was loaded asynchronously successfully.
3. Try navigating via the client view URL to the `/hello.txt` file available in the `/public` folder.
e.g. https://qwikstarterrrx14g-m2gy--5173.local-corp.webcontainer.io/hello.txt
4. Observe that it returns a 404 page, indicating the file does not exist. 

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 14.29 GB / 23.96 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2
    @builder.io/qwik-city: 0.1.0-beta9 => 0.1.0-beta9
    undici: 5.15.0 => 5.15.0
    vite: 4.0.4 => 4.0.4
```

**Comment by DustinJSilk** [comment] 2023-01-17 17:03
If i had to guess, i'd say the dev server is missing a mime type lookup for your static files - we might just need to add a few more to the list [here](https://github.com/BuilderIO/qwik/blob/6976944856716a2e1375f8a4fe4a9e954bfdb0f0/packages/qwik-city/buildtime/vite/dev-server.ts#L337)

**Comment by frammiie** [comment] 2023-01-17 17:11
I would suggest not identifying and limiting static assets via MIME-type.
Surely an alternative approach is desirable/appropriate?

**Comment by gioboa** [comment] 2023-08-26 20:50
@frammiie with Qwik 1.2.10 Is this still an issue?

**Comment by engineersamwell** [comment] 2023-12-11 14:13
I can confirm this is still an issue, I'm trying to reference a local font in my global.css and it fails because woff2 is not part of the mime types:

```
@font-face {
  font-family: MyFont;
  font-style: normal;
  font-weight: 100;
  src:
    url("/fonts/MyFont/MyFont.woff2") format("woff2"),
    url("/fonts/MyFont/MyFont.woff") format("woff");
  unicode-range: U+0-FF, U+131, U+152-153, U+2C6, U+2DA, U+2DC, U+2000-206F,
    U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
```

Error:
```
Request URL:
http://localhost:5173/fonts/MyFont/MyFont.woff2
Request Method:
GET
Status Code:
404 Not Found
```

See https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/buildtime/vite/dev-server.ts#L502

**Comment by gioboa** [comment] 2024-01-24 10:33
@engineersamwell May I ask you to drop a PR for that? Thanks

**Comment by gioboa** [comment] 2024-11-27 17:42
I tried with the latest version and now it's working.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.

**Closed by gioboa** 2024-11-27 17:42 UTC
Labels: TYPE: bug, STATUS-1: needs triage
