### ISSUE TITLE
[🐞] Qwik runtime importing from wrong q:base origin after user interaction in cross-origin container

### ISSUE THREAD

**Issue by jerimiahwelch** [QwikDev/qwik#5050] opened 2023-08-29 14:20 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

Hello,

We are excited to use Qwik Containers to create a Cross-Origin Micro Frontend, but we are seeing that the Qwik runtime is not importing from the specified q:base origin after user interaction. 

As shown in [the qwik containers documentation](https://qwik.builder.io/docs/advanced/containers/), we are inserting a Cross-Origin Qwik Container:

![Screenshot 2023-08-28 at 4 18 28 PM](https://github.com/BuilderIO/qwik/assets/1224514/71a78327-f6ae-4cc0-9ac0-50ebb0c561cf)

Steps to reproduce

1. Load minimal reproduction in Chrome: https://wompme.blob.core.windows.net/7910/qwikContainerCorsImportIssue.html
2. Scroll down to pagination section at bottom of page
3. Click on Page 2

Expected behavior

1. All JS should load from Cross-Origin q:base property of https://care-core.pages.dev/build/

Observed behavior

1. Some JS loads from q:base origin of https://care-core.pages.dev/build/
2. Some JS is loading from page origin of 
https://wompme.blob.core.windows.net/build
![Screenshot 2023-08-28 at 4 28 41 PM](https://github.com/BuilderIO/qwik/assets/1224514/a831f74c-0c83-4f91-8986-f45020188019)

### Reproduction

https://wompme.blob.core.windows.net/7910/qwikContainerCorsImportIssue.html

### Steps to reproduce

See repro steps in description.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 604.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    npm: 9.6.6 - /opt/homebrew/bin/npm
    pnpm: 8.6.10 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.110
    Chrome Canary: 118.0.5976.0
    Safari: 16.5.2
```

**Comment by mhevery** [comment] 2023-08-29 17:24
Cool! Would love to know more about your goals so that I can better prioritize this.
- Are you building something with Qwik in production or are you just exploring? 
- Why do you need to go cross-server?

You can also reach me on [Discord](http://qwik.buidler.io/chat) `@mhevery`

**Comment by mhevery** [comment] 2023-08-31 00:41
OK, I dug into it a bit, and the issue is coming from Vite. 

```typescript
const a = o(_(()=>i(()=>import("./q-0777dc25.js"), ["build/q-0777dc25.js", "build/q-a741c7da.js", "build/q-47bdf09a.js", "build/q-683653e0.js", "build/q-0815ac35.js", "build/q-d2a0a80e.js", "build/q-e4ce1e98.js", "build/q-5b5c912e.js", "build/q-85384b7b.js", "build/q-f2327580.js", "build/q-6db0b552.js", "build/q-6febb18e.js", "build/q-3a50c098.js", "build/q-d42d0c15.js", "build/q-121ac03d.js"]), "s_U4biimqwnQ0"))
```

The problem is that vite sees `q-0777dc25.js` and it knows that `q-0777dc25.js` imports `q-0777dc25.js` (and so on) so it wants to be smart and pre-fetch all of these to avoid the waterfall problem. So it takes the array and inserts it into the DOM as `<link rel="modulepreload" as="script" crossorigin="" href="/build/q-e480eacf.js">` so that the browser does prefetching. But the browser document is on a different domain, hence the errors. Interestingly these are just that, errors, but the application should be fully functional as those fetches have no purpose other than to avoid waterfall. 

![image](https://github.com/BuilderIO/qwik/assets/111951/5d78771b-40db-4ea3-a536-f3a1c6f872b5)

Related issues on this problem: https://github.com/vitejs/vite/issues/5214, https://github.com/vitejs/vite/issues/3133, https://github.com/vitejs/vite/issues/5120, 

Possible fix: https://github.com/vitejs/vite/pull/9938

Add this to your `vite.config.js`
```typescript
    build: {
      modulePreload: {
        resolveDependencies: (url, deps, opts) => {
          return deps.map((v) => 'http://myserver/' + v);
        },
      },
    },

```

https://vitejs.dev/config/build-options.html#build-modulepreload

**Comment by jerimiahwelch** [comment] 2023-08-31 20:17
@mhevery ,

Thank you so much for your time on this! And so quickly too. It's been a whirlwind of a morning, but we will be able to try out this solution by early next week. 


That matches what we were seeing. The functionality was working, but it was making duplicate requests to the origin.

We currently are setting the q:build attribute to match the server at runtime instead of compile time (below), so that q:base will match the deployment environment without the need for config files. We will dig into Vite module preload and try to see if something similar is possible as well.

![Screenshot 2023-08-31 at 1 09 17 PM](https://github.com/BuilderIO/qwik/assets/1224514/e397f2f3-b1cc-42e3-aa9e-4532586fba7b)

**Comment by mhevery** [comment] 2023-08-31 20:44
Can this issue be closed?

**Comment by PatrickJS** [comment] 2024-05-06 18:24
I'm closing this and we're adding better `base` support
https://github.com/QwikDev/qwik/pull/6017

please reopen if there is still an issue

**Closed by PatrickJS** 2024-05-06 18:24 UTC
Labels: TYPE: bug, STATUS-1: needs triage
