### ISSUE TITLE
[🐞] dev build randomly fail

### ISSUE THREAD

**Issue by TicTak21** [QwikDev/qwik#2657] opened 2023-01-17 12:16 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

<img width="910" alt="Screen Shot 2023-01-17 at 14 06 23" src="https://user-images.githubusercontent.com/44474697/212896110-83f9e58d-9032-4980-9df7-616ccb4915d5.png">

```
2:05:44 PM [vite] Internal server error: Cannot read properties of null (reading 'useQwikCityEnv')
  File: /Users/.../node_modules/.pnpm/@builder.io+qwik-city@0.0.128/node_modules/@builder.io/qwik-city/index.qwik.mjs:276:14
  274|  };
  275|  const QwikCityProvider = /* @__PURE__ */ componentQrl(inlinedQrl(() => {
  276|    const env = useQwikCityEnv();
     |                ^
  277|    if (!env?.params)
  278|      throw new Error(`Missing Qwik City Env Data`);
      at QwikCityProvider_component_TxCFOy819ag (/Users/.../node_modules/.pnpm/@builder.io+qwik-city@0.0.128/node_modules/@builder.io/qwik-city/index.qwik.mjs:276:14)
      at invoke (file:///Users/.../node_modules/.pnpm/@builder.io+qwik@0.16.2_undici@5.14.0/node_modules/@builder.io/qwik/core.mjs:706:26)
      at file:///Users/.../node_modules/.pnpm/@builder.io+qwik@0.16.2_undici@5.14.0/node_modules/@builder.io/qwik/core.mjs:6348:28
      at async renderRoot (file:///Users/.../node_modules/.pnpm/@builder.io+qwik@0.16.2_undici@5.14.0/node_modules/@builder.io/qwik/core.mjs:6840:5)
      at async renderSSR (file:///Users/.../node_modules/.pnpm/@builder.io+qwik@0.16.2_undici@5.14.0/node_modules/@builder.io/qwik/core.mjs:6836:5)
      at async Proxy.renderToStream (file:///Users/.../node_modules/.pnpm/@builder.io+qwik@0.16.2_undici@5.14.0/node_modules/@builder.io/qwik/server.mjs:632:3)
      at async /Users/.../node_modules/.pnpm/@builder.io+qwik@0.16.2_undici@5.14.0/node_modules/@builder.io/qwik/optimizer.cjs:1763:28

```
### Steps to reproduce

1) `pnpm create qwik@latest`
2) Edit files
3) Random error

### System Info

```shell
System:
    OS: macOS 10.15.7
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.11.14.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 108.0.5359.124
    Firefox: 104.0.2
    Safari: 14.1.1
```

**Comment by TicTak21** [comment] 2023-01-18 13:12
Yes, it works fine after saving, but I think it shouldn't have happened in the first place.
It's annoying and I can't find any related information on how to fix it.

**Comment by manucorporat** [comment] 2023-01-20 10:26
Looking!

**Comment by genki** [comment] 2023-02-03 20:26
I have met this issue so tried to retrieve the cause.
While `useQwikCityEnv()` calls `useServerData("qwikcity")` and the code follows:

```ts
export function useServerData(key: string, defaultValue?: any) {     
  const ctx = useInvokeContext();                                                                                   
  return ctx.$renderCtx$.$static$.$containerState$.$serverData$[key] ?? defaultValue;                                                                        
}
```

So I checked the `ctx.$renderCtx$.$static$.$containerState$.$serverData$` by `console.log()` and got value below:
```ts
'$serverData$': { url: 'http://localhost:5173/' },
```

There's no `"qwikcity"` key and value.

**Comment by vladimirgal1012** [comment] 2023-02-04 12:05
@manucorporat Hi, any updates on this one ? It keeps happening quite frequently.

**Comment by TicTak21** [comment] 2023-03-10 16:35
Updates?

**Comment by KaanSali** [comment] 2023-05-10 19:34
Still have this issue at version 1.0. I think it started after installing partytown integration.

**Comment by VinSpee** [comment] 2023-08-03 12:44
I can confirm seeing this on latest (`1.2.6`) when the Partytown integration (`0.8.0`) is present in the tree.

**Comment by rodmoreno** [comment] 2023-09-10 10:24
I can confirm too seeing this on latest (`1.2.10`) with Partytown integration (`0.8.1`) is present in the tree.

**Comment by mhevery** [comment] 2023-09-11 17:34
This is a very generic reproduction step Could we have something which is more predictable? Hard to fix if we don't have consistant reproduction.

**Comment by rodrigotonso** [comment] 2023-11-24 04:21
When I had that issue with Partytown, clearing the cache helped me.
<img width="575" alt="Captura de pantalla 2023-11-24 a la(s) 01 19 15" src="https://github.com/BuilderIO/qwik/assets/67134489/598209c2-6e76-439e-8103-df6ce74d8236">

**Comment by PatrickJS** [comment] 2024-05-06 03:39
closing for https://github.com/QwikDev/qwik/issues/6237

**Closed by PatrickJS** 2024-05-06 03:39 UTC
Labels: TYPE: bug, STATUS-2: waiting for core
