### ISSUE TITLE
[🐞] Stores without writers don't get serialized

### ISSUE THREAD

**Issue by Hcu** [QwikDev/qwik#5948] opened 2024-03-05 03:56 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I have a component that renders search results.
The search results will be rendered as list items that will have a onclick$ event handler attached.

```
return (
    <>
          <button onClick$={()=> searchResults.value = [...searchResults.value, "Item x"] }>Simulate search</button>
          <p>Search results</p>
          <ul>
             {searchResults.value.map((album) => (
               <li><span onClick$={ () => addToCart(album)}>Click to add to cart</span></li>
           ))}
          </ul>
          <input id="removeMeAndResultsCannotBeAdded" hidden="hidden" onClick$={()=>addToCart("dummy") }/>
          
    </>
  );
```

Initially the searchResults are 'empty'.

I believe this causes the optimizer to 'tree shake' the onclick$ handler as there aren't any html elements that need its presence.

A workaround is to create a 'hidden input' with the same onclick$ handler defined, which prevents the optimizer from stripping away the event callback.
Without this hidden input, there is no onclick$ triggered when clicking on a search result.

### Reproduction

https://qwik.dev/playground/#f=7VdNj9MwEL3vr7By2USqXNgjSozKnvbAaeFU9ZAlWTWi%2BVBpgKrKf%2BfNjJPY%2BQCuSOSSL8%2FYnvdm5tkhzcMbdPshtkTezZRk%2BDDQYjO0Yn6a8FP%2BcmHbKIxloD9bAxt7166HMZjCHoyhHJvZI1owh1Fx7aFW8E7tzuf0Ggt2Blh5AJBFP1Uyyx36a8J7ut0jLndi8yyFGMOXckHGpKeXFtU0cdPVmQvO%2BpG%2BAGEDiU%2B4PzjD0iz7VPP%2BEoXpqFhHiZG92tl0v2fdtN%2BOMoQcdNHdKrOEIKzcRsFyC%2BHaX5hGWUPDStRea2Tx7M9GBU8kLH4GB9WZ56JsT9Q4ZeSgDd1JG2PjaBsa1Qv3f3tyX3HdFqbVkFRhyNtnAGR3zhWfChOzkhx3Z9NtiKi17wwPUJeaftHtC37GW7I28RaOXOdR1Lmr3frLjQtWmkWWBOe8rL%2FnH%2FNdRU2Zlv6YVlV9%2BZDvsizPAnUscK%2BSQO7BBIZxlUHWluU1iFQ3ZC9dk9QdadrTDT1vjas9uWijv%2BfqhD8zDjGgTE%2BREaF0%2B9RXLX1sWYPaAEdYvIf8EvYuDchopDoTgKm%2BiP8yGcyNLLo1bL3LB3oKtQR%2BDP3f9ct53OXsIvWGWnNfvPYHcksWC73eAQkVmGIpQ1fwooOat5W3WhiP3CdhP2StTUxbFoBTUzc2n2uoR%2BbhRI5qz%2FGDhjy2nlcpQE80LS2cCpQT4tlK%2BassC3DZhwksM6MVN05ewJf79keHjYEahXSGLE1t3qL7UKa%2FFjnOAVDAHEjZ8AC9Vk%2Bv6lq3CAHVAoxJAdjlnCOgx%2FQrnX9%2FFJDpJOPplEE%2Bxnpf5pdjnUkbfMn5sNzLyey9xJk%2BLoSanVa1OuHETCI8xavvmz7RKclLQWfnA63%2Fa7h%2FT8P9Ag

### Steps to reproduce

Please have a look at the qwik playground link.

The steps to reproduce are described in the playground as well, but basically...

1. Click on the 'Simulate search' button.
2. Click on a search result and see how it will get added to the 'cart' on the page.
3. Remove the `<input hidden="hidden">` field on the Search component.
4. Click on the 'Simulate search' button.
5 Clicking on a search result no longer adds item to the 'cart' 

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.64 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: ^1.4.5 => 1.4.5 
    @builder.io/qwik-auth: 0.1.1 => 0.1.1 
    @builder.io/qwik-city: ^1.4.5 => 1.4.5 
    undici: * => 6.7.0 
    vite: ^5.0.12 => 5.1.4
```

**Comment by gioboa** [comment] 2024-03-05 06:48
Thanks for reporting this edge case. We are working on Qwik v2 and this kind of scenarios are useful to improve the framework. I'll recreate the test in v2.

**Comment by wmertens** [comment] 2024-03-05 08:32
Note that it's somewhat different, what's happening is that the cart doesn't get listened to in root because nothing can change it.

Here's a simplified repo that shows it. As you can see from the console logs, the click handlers work correctly, it's just the cart that doesn't update root.

https://qwik.dev/playground/#f=7VdNb9swDL33Vwi5OAYMZ%2BthwLokwLDTBmw7dLcgA9R8NEbSuEidFYHh%2F75HUrZFyy56LVBdEkuURFLvUU8eaK4%2FfPrsoUbDK%2FEAkTSXMP%2FrIFNGuaQlRmydRX1Uo%2B7RjpAuRsI3XK1Ik2iFxVLnkAbrlWYB%2FGl0Po7oJ0JoVzLnVmopzD04lx0xUN0gXtV107hgqubIjPNjJU56%2FPQ8w9a1ZS09IlfQaV6UmB%2B3v3%2Blsny2vYypN4695e16%2FSd3iYCzVK09F9gOg%2Bnj%2BWkng7JjFV%2FxrwKWApf7fJy7pLgLhvirLc4H3UGtVPlJoXA819rN1DqHLFynWY8mV8Asi8lWQ5VCkSYJskk1vBC1r2tcrjnnZdCu0a39vk76nI3jSmdm4qdGaCQNmoZ0shdHE0HVkpDt%2FpqfOa7zgu48iMQNabScBdf2ZO9ZfSDo6MnkewoK1yhbsxqiUcEKsZdg%2FpqqHQJXFLRQZrGUFXvuGA%2FX4D8BtUV30QgUWZEJP15E2zyPlvEXipQ0OH8jREg%2BSBHE82D3CLkwz%2Flpb%2Bw9ZENIGKqwL9NlAOr0RFEn9jGFfiM5AoxRDh30BQrTu5N%2FNtSuPXvrIiSvcZrktDsocsJN1vgYQLPLVArJADE4M4sRoXq07IG1ONhBXY1c3e1iUcSclWovhb3%2BDLmawAVHlOFYBJzVQrTNAp4VjmxxUDsG6we1kgvXa0pHXT6m9DacS62YTvijn6nUumwNGSs9QQoQfjARahR4BUUtHk3%2FCMAefBqWpeb71lzyM4Q2SAqAQFgmwVrFaYP37M7u6QH8nEGnrywoAxkKmCOVR%2FzQKwnvApdYc7cREwztaNYKT%2BTVzh6hejmJwR7wY0eFIjtmBSRoDbmEqUZbMt%2FwPniwh8NFz1en6OWnrjHvwu4NCrv%2F

You're the first to report this edge case AFAIK (although others may have encountered it without realizing). The v1 code around this is quite hairy, I can't find the problematic area, so most likely we'll just make sure this works correctly in v2.

**Comment by gioboa** [comment] 2024-03-05 13:10
I tried to reproduce the problem in qwik.new and it's working fine :thinking:

**Comment by wmertens** [comment] 2024-03-05 13:18
@gioba did you use the version I posted above? It has `'foo'` as an initial item which makes it not fail. I'll update the link so it fails

**Comment by gioboa** [comment] 2024-03-05 13:23
No, I used the one in the first commit

**Comment by wmertens** [comment] 2024-03-05 13:30
Can you use mine

**Comment by gioboa** [comment] 2024-03-05 13:43
> Can you use mine

Your example is working too in qwik.new :thinking:

**Comment by wmertens** [comment] 2024-03-05 15:49
Super weird - you can see it failing in the playground right?

**Comment by gioboa** [comment] 2024-03-05 20:53
> Super weird - you can see it failing in the playground right?

Yep, it's failing. I'll add a test in Qwik v2 for that.

**Comment by wmertens** [comment] 2024-11-01 11:39
The original issue is fixed in v2, but now there's a new bug: When you add `foo` initially and click Search, it replaces the found `foo` with `item` but the button will still add `foo` :zany_face: 

https://qwikdev-build-v2.qwik-8nx.pages.dev/playground/#f=7VdNa9tAEL3nVyy6yAIh40AvqW0oPbXQ9pDejAsbf0TCjhUcucEI%2Ffe%2B2VmtdrRSyTWQvdiSZmdnZt%2BbfeuB5nY2%2B%2BShRsIr9QCRukPY%2FOshk7%2BalpYqtrUW7VZF%2Fa2NUC6DhK84WlEm1gqrtawhfWw9LQL409flJKafGKnd8Jx77qUw9%2BBc98RAc4d8xas7F4Jq3JYpG8eGg%2FT46UWGpVvLVnrEtqHTvDhV3%2B9%2F%2FczYfbG%2FTuhtknju9Xb7u7SFQLDUrb0QAucwhyf4NYadDRxkz5eXnB1wVE1yY34F%2BAQA7ePz0hbOHkLEcWlxOcoXNGpRwwwqyAu%2FW0z4ORahH%2BePJjfAtRGcnc6qmUauULxIM%2B6IxpftVkXsMVJVaQo0OsGJ3OGgp0NRJ0kjSzT1awTOKfcABUSq2svI5dJ0lDV2f9SPEod%2FRSckJOWOFF1p5Nn%2BrB%2BNVkH68YsqD5QVDl1jbbQTfWVEENeJFG%2Fp8SHMWW8zwVZr9jhwInksQLcgWHdcqJycYY%2BmPUxW8b4s43XymTIlxW6ekSIEIoQL8nnSB6RcqdfyfFD6ESIjpBf14%2F%2BTawT03r2IxyyD2iPxArRRDS0JGAvzh7O%2FNzRuPXttM6SosZsUtN0oCsJOlgAZwbWtVAaBAem4UKuIUButBwDOAfZg10JXvra5CIouarGWwN5whWx3MO2JdeSE5Z6WsrWrAi4hlm1J0EVGOwmN2rSwtzSRtpHM6Sa5ZI7Pp%2BZhmKo0%2BnQNKStuxCL9YCK0K%2FAKimpcsf4SgD34OJZl6tteXcsLZDlICoBAhqaBr%2Bq8w%2B031we6Lr8WUPUbDcpAtALmKOUJP3Snwi3CFlY97NgEn3KatcGFepPrEzSyKWKwBuLIqVEUp6KCYG0hR4cIL2n4htvEkz4er3K%2B2EWvPm2P%2BZCB71AG%2FgM

@Varixo

**Comment by wmertens** [comment] 2024-11-01 11:44
I'll open a new issue for the new issue, and close this. It's not fixed in v1 but it is fixed in v2.

**Closed by wmertens** 2024-11-01 11:44 UTC
Labels: TYPE: bug, WAITING FOR: team, VERSION: upcoming major
