### ISSUE TITLE
[🐞] Error: Missing Qwik City Env Data

### ISSUE THREAD

**Issue by Nefcanto** [QwikDev/qwik#5939] opened 2024-03-04 11:31 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to load settings and configuration dynamically. I want to not use `.env` and `.env.production` file to prevent settings being injected and hardcoded into the build output.

I have tried to use `fs` to read settings. It works in the development environment. But when I go to the production, I get this error:

```
Error: Missing Qwik City Env Data
    at AsyncFunction.Aa (file:///Temp/server/q-DNo4f3Gn.js:15:11868)
    at AsyncFunction.dc (file:///Temp/server/q-DNo4f3Gn.js:10:5874)
    at AsyncFunction.V (file:///Temp/server/q-DNo4f3Gn.js:10:5808)
    at file:///Temp/server/q-DNo4f3Gn.js:15:2935
    at q (file:///Temp/server/q-DNo4f3Gn.js:7:1510)
    at file:///Temp/server/q-DNo4f3Gn.js:15:2804
    at file:///Temp/server/q-DNo4f3Gn.js:8:4693
    at Qt (file:///Temp/server/q-DNo4f3Gn.js:7:1430)
    at Et (file:///Temp/server/q-DNo4f3Gn.js:8:4686)
    at wi (file:///Temp/server/q-DNo4f3Gn.js:8:9122)

Node.js v20.11.0

```

### Reproduction

https://github.com/Nefcanto/QwikMissingQwikCityEnvData

### Steps to reproduce

1. `git clone http://github.com/Nefcanto/QwikMissingQwikCityEnvData`
2. `cd QwikMissingQwikCityEnvData`
3. `npm install --legacy-peer-deps`
4. `npm run dev`
5. You should be able to see the site in the browser if you navigate to `https://localhost:5173`
6. Now let's build the site
7. `npm run build`
8. `node server/entry.express.js`
9. Now you should see this error:

```
Error: Missing Qwik City Env Data
    at AsyncFunction.Aa (file:///Temp/server/q-DNo4f3Gn.js:15:11868)
    at AsyncFunction.dc (file:///Temp/server/q-DNo4f3Gn.js:10:5874)
    at AsyncFunction.V (file:///Temp/server/q-DNo4f3Gn.js:10:5808)
    at file:///Temp/server/q-DNo4f3Gn.js:15:2935
    at q (file:///Temp/server/q-DNo4f3Gn.js:7:1510)
    at file:///Temp/server/q-DNo4f3Gn.js:15:2804
    at file:///Temp/server/q-DNo4f3Gn.js:8:4693
    at Qt (file:///Temp/server/q-DNo4f3Gn.js:7:1430)
    at Et (file:///Temp/server/q-DNo4f3Gn.js:8:4686)
    at wi (file:///Temp/server/q-DNo4f3Gn.js:8:9122)

Node.js v20.11.0
```

### System Info

```shell
System:
    OS: Linux 6.5 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 9.17 GB / 15.35 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.9.2 => 0.9.2 
    @builder.io/qwik: ^1.4.5 => 1.4.5 
    @builder.io/qwik-auth: ^0.1.3 => 0.1.3 
    @builder.io/qwik-city: ^1.4.5 => 1.4.5 
    undici: ^6.6.2 => 6.7.0 
    vite: ^5.1.4 => 5.1.4
```

### Additional Information

We have three different modes for Qwik: dev, preview, and build.
Based on our experience, these differ from each other.
Please make them work as much the same as possible. If something works using `npm run dev` it should work for `npm run build`.

**Comment by wmertens** [comment] 2024-03-05 09:11
This sounds like some sort of import order issue maybe? Not sure how your additions cause this to break.

It's probably happening [here](https://github.com/BuilderIO/qwik/blob/3ba872ebcca9a695144445811309c9fa264f5a27/packages/qwik-city/runtime/src/qwik-city-component.tsx#L91), which uses [useQwikCityEnv](https://github.com/BuilderIO/qwik/blob/3ba872ebcca9a695144445811309c9fa264f5a27/packages/qwik-city/runtime/src/use-functions.ts#L37), which uses [useServerData](https://github.com/BuilderIO/qwik/blob/3ba872ebcca9a695144445811309c9fa264f5a27/packages/qwik/src/core/use/use-env-data.ts#L10), which is injected into the render function by qwik-city [here](https://github.com/BuilderIO/qwik/blob/3ba872ebcca9a695144445811309c9fa264f5a27/packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts#L448) which generates it from the incoming requests [here](https://github.com/BuilderIO/qwik/blob/3ba872ebcca9a695144445811309c9fa264f5a27/packages/qwik-city/middleware/request-handler/response-page.ts#L12).

**Comment by Nefcanto** [comment] 2024-03-05 10:47
@wmertens, because we want to have dynamic settings, one thing we tried was to return a function that returns the render function in `entry.ssr.tsx`. In other words, converting this:

```
export default function (opts: RenderToStreamOptions) {
    return renderToStream(<Root />, {
        manifest,
        ...opts,
        // Use container attributes to set attributes on the html tag.
        containerAttributes: {
            lang: opts.serverData?.locale || "en",
            ...opts.containerAttributes,
        },
    });
}
```

to this:

```
export default function (props) {
    function render(opts: RenderToStreamOptions) {
        return renderToStream(<Root {...props} />, {
            manifest,
            ...opts,
            containerAttributes: {
                lang: opts.serverData?.locale || "en",
                ...opts.containerAttributes,
            },
        });
    }
    return render(props)
}
```

And changing this line in `entry.express.ts`, from this:

```
const { router, notFound } = createQwikCity({ render, qwikCityPlan, manifest });
```
to this:

```
const props = {} // reading settings dynamically in express layer, rather than Qwik layer when the app wants to start
const render = renderer(props)
const { router, notFound } = createQwikCity({ render, qwikCityPlan, manifest });
```

And that caused this error. But that's a totally valid JavaScript code. What could be wrong here?

**Comment by wmertens** [comment] 2024-03-05 12:48
Seems ok, you'll have to step through it to figure it the problem.

**Comment by Nefcanto** [comment] 2024-03-05 13:26
@wmertens, I have done it a couple of times. But I can't find out the problem. That's why I have submitted an issue. The error is very vague.

**Comment by wmertens** [comment] 2024-03-05 13:29
Myeah, better to do the dynamic environment like I explained in the other issue.

**Comment by GrandSchtroumpf** [comment] 2024-03-06 08:21
This happens to me when opening the console in the devtools of Firefox with this additional warning in the console:
```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://356a5cca-d12d-4591-83bc-b31caa7d6363/inject.js
Source Map URL: inject.js.map
```

**Comment by Dindaleon** [comment] 2024-03-07 18:08
This is happening to me with a fresh install.

**Comment by RaeesBhatti** [comment] 2024-03-23 23:16
I ran into this when using QwikPartytown integration as well. Here's a reproduction: https://stackblitz.com/edit/qwik-starter-7l7lf7?file=src%2Froot.tsx


The above link only runs into an error when you click the reload icon. You'll be able to see the error in terminal.
<img width="1488" alt="Screenshot 2024-03-23 at 7 16 05 PM" src="https://github.com/BuilderIO/qwik/assets/10067728/e168722a-d318-4157-b330-f19c6109a461">

**Comment by ahme-dev** [comment] 2024-03-24 16:01
I faced the same issue, but it was only due to the hostname/domain (localhost) having data of previous app stored in it. It solved itself when I cleared cookies and site data

**Comment by ogdakke** [comment] 2024-04-28 13:30
> I faced the same issue, but it was only due to the hostname/domain (localhost) having data of previous app stored in it. It solved itself when I cleared cookies and site data

This fixed the issue for me aswell. Thanks

**Comment by PatrickJS** [comment] 2024-05-06 03:37
closing this for https://github.com/QwikDev/qwik/issues/6237

**Closed by PatrickJS** 2024-05-06 03:37 UTC
Labels: TYPE: bug, STATUS-1: needs triage

**Comment by JerryWu1234** [comment] 2024-06-03 11:03
> I ran into this when using QwikPartytown integration as well. Here's a reproduction: https://stackblitz.com/edit/qwik-starter-7l7lf7?file=src%2Froot.tsx
> 
> The above link only runs into an error when you click the reload icon. You'll be able to see the error in terminal. <img alt="Screenshot 2024-03-23 at 7 16 05 PM" width="1488" src="https://private-user-images.githubusercontent.com/10067728/316273796-e168722a-d318-4157-b330-f19c6109a461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTI3MDQsIm5iZiI6MTcxNzQxMjQwNCwicGF0aCI6Ii8xMDA2NzcyOC8zMTYyNzM3OTYtZTE2ODcyMmEtZDMxOC00MTU3LWIzMzAtZjE5YzYxMDlhNDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDExMDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NmQ4Y2FjODU0OWNhMjUzMjhlZjg0ODEyZDdkNjRhN2I1MmI3MDY1MmViMWQxMGExNDRkNDNkNGJmOTFlZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fbY4SctRlLIbnbUSLJuIfVbszLni-OfCy826O60cgpQ">

![image](https://github.com/QwikDev/qwik/assets/27261522/cb7b8426-22ff-4f52-b36e-e27da1622fcc)

this link is right. no error in this link
