### ISSUE TITLE
[🐞] AWS Lambda adapter is broken (cjs)

### ISSUE THREAD

**Issue by kerbelp** [QwikDev/qwik#5380] opened 2023-11-01 05:56 UTC
### Which component is affected?

Starters / CLI

### Describe the bug

**What I did:**
1. I created a new project using the command: `npm create qwik@latest`
2. I added aws lambda integration using `npm run qwik add` and chose *Adapter: AWS Lambda (AWS Lambda)* with all the defaults
3. I ran `npm run serve` and everything works as locally
4. I ran `npm run deploy` 

**What I expected**
That the lambda will serve the same html as it did locally

**What happened:**
Lambda crashed and returned 500 internal server error with the following message:
```
{
message:"require() of ES Module /var/task/server/entry_aws-lambda.js from /var/task/s_qwik_app.js not supported.
Instead change the require of entry_aws-lambda.js in /var/task/s_qwik_app.js to a dynamic import() which is available in all CommonJS modules."
name:"Error"
type:"ERROR_TYPE_UNCAUGHT"
}
```

### Reproduction

https://github.com/kerbelp/qwik-aws-lambda

### Steps to reproduce

1. `npm create qwik@latest`
2. `npm run qwik add` and choose *Adapter: AWS Lambda (AWS Lambda)* with all the defaults
3. `npm run deploy` 

### System Info

```shell
The problem is on AWS, not locally.
```

**Comment by gioboa** [comment] 2023-11-01 07:42
Hi @kerbelp, to solve the problem is fundamental to have an AWS environment so it's hard for us to recreate the scenario.
Can you help us and drop a PR for this please?

**Comment by kerbelp** [comment] 2023-11-01 08:01
Thanks for commenting @gioboa. sure, how can I help?

**Comment by gioboa** [comment] 2023-11-01 08:09
I can guide you on how investigate the problem, drop me a message in the [Qwik discord server](https://qwik.builder.io/chat) please.

**Comment by PatrickJS** [comment] 2024-05-07 05:09
I'm closing since this should be fine in latest and ESM. qwik requires node 18+ now (I recommend node 20)

**Closed by PatrickJS** 2024-05-07 05:09 UTC
Labels: TYPE: bug, STATUS-1: needs triage
